// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AbilityMixinRecoverInfo.proto
// Protobuf Java Version: 4.27.2

package io.irminsul.common.proto;

public final class AbilityMixinRecoverInfoOuterClass {
  private AbilityMixinRecoverInfoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      AbilityMixinRecoverInfoOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AbilityMixinRecoverInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AbilityMixinRecoverInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 instanced_ability_id = 1;</code>
     * @return Whether the instancedAbilityId field is set.
     */
    boolean hasInstancedAbilityId();
    /**
     * <code>uint32 instanced_ability_id = 1;</code>
     * @return The instancedAbilityId.
     */
    int getInstancedAbilityId();

    /**
     * <code>uint32 instanced_modifier_id = 2;</code>
     * @return Whether the instancedModifierId field is set.
     */
    boolean hasInstancedModifierId();
    /**
     * <code>uint32 instanced_modifier_id = 2;</code>
     * @return The instancedModifierId.
     */
    int getInstancedModifierId();

    /**
     * <code>uint32 local_id = 3;</code>
     * @return The localId.
     */
    int getLocalId();

    /**
     * <code>repeated uint32 data_list = 4;</code>
     * @return A list containing the dataList.
     */
    java.util.List<Integer> getDataListList();
    /**
     * <code>repeated uint32 data_list = 4;</code>
     * @return The count of dataList.
     */
    int getDataListCount();
    /**
     * <code>repeated uint32 data_list = 4;</code>
     * @param index The index of the element to return.
     * @return The dataList at the given index.
     */
    int getDataList(int index);

    /**
     * <code>bool is_serverbuff_modifier = 5;</code>
     * @return The isServerbuffModifier.
     */
    boolean getIsServerbuffModifier();

    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    java.util.List<MassivePropSyncInfoOuterClass.MassivePropSyncInfo>
        getMassivePropListList();
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    MassivePropSyncInfoOuterClass.MassivePropSyncInfo getMassivePropList(int index);
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    int getMassivePropListCount();
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    java.util.List<? extends MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder>
        getMassivePropListOrBuilderList();
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder getMassivePropListOrBuilder(
        int index);

    /**
     * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
     * @return Whether the breakoutSnapShot field is set.
     */
    boolean hasBreakoutSnapShot();
    /**
     * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
     * @return The breakoutSnapShot.
     */
    BreakoutSnapShotOuterClass.BreakoutSnapShot getBreakoutSnapShot();
    /**
     * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
     */
    BreakoutSnapShotOuterClass.BreakoutSnapShotOrBuilder getBreakoutSnapShotOrBuilder();

    AbilityMixinRecoverInfo.SourceCase getSourceCase();
  }
  /**
   * <pre>
   * Obf: NNBAGDGFEKA
   * </pre>
   *
   * Protobuf type {@code AbilityMixinRecoverInfo}
   */
  public static final class AbilityMixinRecoverInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AbilityMixinRecoverInfo)
      AbilityMixinRecoverInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        AbilityMixinRecoverInfo.class.getName());
    }
    // Use AbilityMixinRecoverInfo.newBuilder() to construct.
    private AbilityMixinRecoverInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AbilityMixinRecoverInfo() {
      dataList_ = emptyIntList();
      massivePropList_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AbilityMixinRecoverInfoOuterClass.internal_static_AbilityMixinRecoverInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AbilityMixinRecoverInfoOuterClass.internal_static_AbilityMixinRecoverInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AbilityMixinRecoverInfo.class, Builder.class);
    }

    private int bitField0_;
    private int sourceCase_ = 0;
    @SuppressWarnings("serial")
    private Object source_;
    public enum SourceCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      INSTANCED_ABILITY_ID(1),
      INSTANCED_MODIFIER_ID(2),
      SOURCE_NOT_SET(0);
      private final int value;
      private SourceCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static SourceCase valueOf(int value) {
        return forNumber(value);
      }

      public static SourceCase forNumber(int value) {
        switch (value) {
          case 1: return INSTANCED_ABILITY_ID;
          case 2: return INSTANCED_MODIFIER_ID;
          case 0: return SOURCE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public SourceCase
    getSourceCase() {
      return SourceCase.forNumber(
          sourceCase_);
    }

    public static final int INSTANCED_ABILITY_ID_FIELD_NUMBER = 1;
    /**
     * <code>uint32 instanced_ability_id = 1;</code>
     * @return Whether the instancedAbilityId field is set.
     */
    @Override
    public boolean hasInstancedAbilityId() {
      return sourceCase_ == 1;
    }
    /**
     * <code>uint32 instanced_ability_id = 1;</code>
     * @return The instancedAbilityId.
     */
    @Override
    public int getInstancedAbilityId() {
      if (sourceCase_ == 1) {
        return (Integer) source_;
      }
      return 0;
    }

    public static final int INSTANCED_MODIFIER_ID_FIELD_NUMBER = 2;
    /**
     * <code>uint32 instanced_modifier_id = 2;</code>
     * @return Whether the instancedModifierId field is set.
     */
    @Override
    public boolean hasInstancedModifierId() {
      return sourceCase_ == 2;
    }
    /**
     * <code>uint32 instanced_modifier_id = 2;</code>
     * @return The instancedModifierId.
     */
    @Override
    public int getInstancedModifierId() {
      if (sourceCase_ == 2) {
        return (Integer) source_;
      }
      return 0;
    }

    public static final int LOCAL_ID_FIELD_NUMBER = 3;
    private int localId_ = 0;
    /**
     * <code>uint32 local_id = 3;</code>
     * @return The localId.
     */
    @Override
    public int getLocalId() {
      return localId_;
    }

    public static final int DATA_LIST_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList dataList_ =
        emptyIntList();
    /**
     * <code>repeated uint32 data_list = 4;</code>
     * @return A list containing the dataList.
     */
    @Override
    public java.util.List<Integer>
        getDataListList() {
      return dataList_;
    }
    /**
     * <code>repeated uint32 data_list = 4;</code>
     * @return The count of dataList.
     */
    public int getDataListCount() {
      return dataList_.size();
    }
    /**
     * <code>repeated uint32 data_list = 4;</code>
     * @param index The index of the element to return.
     * @return The dataList at the given index.
     */
    public int getDataList(int index) {
      return dataList_.getInt(index);
    }
    private int dataListMemoizedSerializedSize = -1;

    public static final int IS_SERVERBUFF_MODIFIER_FIELD_NUMBER = 5;
    private boolean isServerbuffModifier_ = false;
    /**
     * <code>bool is_serverbuff_modifier = 5;</code>
     * @return The isServerbuffModifier.
     */
    @Override
    public boolean getIsServerbuffModifier() {
      return isServerbuffModifier_;
    }

    public static final int MASSIVE_PROP_LIST_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private java.util.List<MassivePropSyncInfoOuterClass.MassivePropSyncInfo> massivePropList_;
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    @Override
    public java.util.List<MassivePropSyncInfoOuterClass.MassivePropSyncInfo> getMassivePropListList() {
      return massivePropList_;
    }
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    @Override
    public java.util.List<? extends MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder>
        getMassivePropListOrBuilderList() {
      return massivePropList_;
    }
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    @Override
    public int getMassivePropListCount() {
      return massivePropList_.size();
    }
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    @Override
    public MassivePropSyncInfoOuterClass.MassivePropSyncInfo getMassivePropList(int index) {
      return massivePropList_.get(index);
    }
    /**
     * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
     */
    @Override
    public MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder getMassivePropListOrBuilder(
        int index) {
      return massivePropList_.get(index);
    }

    public static final int BREAKOUT_SNAP_SHOT_FIELD_NUMBER = 7;
    private BreakoutSnapShotOuterClass.BreakoutSnapShot breakoutSnapShot_;
    /**
     * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
     * @return Whether the breakoutSnapShot field is set.
     */
    @Override
    public boolean hasBreakoutSnapShot() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
     * @return The breakoutSnapShot.
     */
    @Override
    public BreakoutSnapShotOuterClass.BreakoutSnapShot getBreakoutSnapShot() {
      return breakoutSnapShot_ == null ? BreakoutSnapShotOuterClass.BreakoutSnapShot.getDefaultInstance() : breakoutSnapShot_;
    }
    /**
     * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
     */
    @Override
    public BreakoutSnapShotOuterClass.BreakoutSnapShotOrBuilder getBreakoutSnapShotOrBuilder() {
      return breakoutSnapShot_ == null ? BreakoutSnapShotOuterClass.BreakoutSnapShot.getDefaultInstance() : breakoutSnapShot_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (sourceCase_ == 1) {
        output.writeUInt32(
            1, (int)((Integer) source_));
      }
      if (sourceCase_ == 2) {
        output.writeUInt32(
            2, (int)((Integer) source_));
      }
      if (localId_ != 0) {
        output.writeUInt32(3, localId_);
      }
      if (getDataListList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(dataListMemoizedSerializedSize);
      }
      for (int i = 0; i < dataList_.size(); i++) {
        output.writeUInt32NoTag(dataList_.getInt(i));
      }
      if (isServerbuffModifier_ != false) {
        output.writeBool(5, isServerbuffModifier_);
      }
      for (int i = 0; i < massivePropList_.size(); i++) {
        output.writeMessage(6, massivePropList_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(7, getBreakoutSnapShot());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sourceCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(
              1, (int)((Integer) source_));
      }
      if (sourceCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(
              2, (int)((Integer) source_));
      }
      if (localId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, localId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dataList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataList_.getInt(i));
        }
        size += dataSize;
        if (!getDataListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataListMemoizedSerializedSize = dataSize;
      }
      if (isServerbuffModifier_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isServerbuffModifier_);
      }
      for (int i = 0; i < massivePropList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, massivePropList_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getBreakoutSnapShot());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AbilityMixinRecoverInfo)) {
        return super.equals(obj);
      }
      AbilityMixinRecoverInfo other = (AbilityMixinRecoverInfo) obj;

      if (getLocalId()
          != other.getLocalId()) return false;
      if (!getDataListList()
          .equals(other.getDataListList())) return false;
      if (getIsServerbuffModifier()
          != other.getIsServerbuffModifier()) return false;
      if (!getMassivePropListList()
          .equals(other.getMassivePropListList())) return false;
      if (hasBreakoutSnapShot() != other.hasBreakoutSnapShot()) return false;
      if (hasBreakoutSnapShot()) {
        if (!getBreakoutSnapShot()
            .equals(other.getBreakoutSnapShot())) return false;
      }
      if (!getSourceCase().equals(other.getSourceCase())) return false;
      switch (sourceCase_) {
        case 1:
          if (getInstancedAbilityId()
              != other.getInstancedAbilityId()) return false;
          break;
        case 2:
          if (getInstancedModifierId()
              != other.getInstancedModifierId()) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCAL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLocalId();
      if (getDataListCount() > 0) {
        hash = (37 * hash) + DATA_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getDataListList().hashCode();
      }
      hash = (37 * hash) + IS_SERVERBUFF_MODIFIER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsServerbuffModifier());
      if (getMassivePropListCount() > 0) {
        hash = (37 * hash) + MASSIVE_PROP_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getMassivePropListList().hashCode();
      }
      if (hasBreakoutSnapShot()) {
        hash = (37 * hash) + BREAKOUT_SNAP_SHOT_FIELD_NUMBER;
        hash = (53 * hash) + getBreakoutSnapShot().hashCode();
      }
      switch (sourceCase_) {
        case 1:
          hash = (37 * hash) + INSTANCED_ABILITY_ID_FIELD_NUMBER;
          hash = (53 * hash) + getInstancedAbilityId();
          break;
        case 2:
          hash = (37 * hash) + INSTANCED_MODIFIER_ID_FIELD_NUMBER;
          hash = (53 * hash) + getInstancedModifierId();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AbilityMixinRecoverInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AbilityMixinRecoverInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AbilityMixinRecoverInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AbilityMixinRecoverInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AbilityMixinRecoverInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AbilityMixinRecoverInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AbilityMixinRecoverInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static AbilityMixinRecoverInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static AbilityMixinRecoverInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static AbilityMixinRecoverInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AbilityMixinRecoverInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static AbilityMixinRecoverInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AbilityMixinRecoverInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Obf: NNBAGDGFEKA
     * </pre>
     *
     * Protobuf type {@code AbilityMixinRecoverInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AbilityMixinRecoverInfo)
        AbilityMixinRecoverInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AbilityMixinRecoverInfoOuterClass.internal_static_AbilityMixinRecoverInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AbilityMixinRecoverInfoOuterClass.internal_static_AbilityMixinRecoverInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AbilityMixinRecoverInfo.class, Builder.class);
      }

      // Construct using io.irminsul.common.proto.AbilityMixinRecoverInfoOuterClass.AbilityMixinRecoverInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getMassivePropListFieldBuilder();
          getBreakoutSnapShotFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        localId_ = 0;
        dataList_ = emptyIntList();
        isServerbuffModifier_ = false;
        if (massivePropListBuilder_ == null) {
          massivePropList_ = java.util.Collections.emptyList();
        } else {
          massivePropList_ = null;
          massivePropListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        breakoutSnapShot_ = null;
        if (breakoutSnapShotBuilder_ != null) {
          breakoutSnapShotBuilder_.dispose();
          breakoutSnapShotBuilder_ = null;
        }
        sourceCase_ = 0;
        source_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AbilityMixinRecoverInfoOuterClass.internal_static_AbilityMixinRecoverInfo_descriptor;
      }

      @Override
      public AbilityMixinRecoverInfo getDefaultInstanceForType() {
        return AbilityMixinRecoverInfo.getDefaultInstance();
      }

      @Override
      public AbilityMixinRecoverInfo build() {
        AbilityMixinRecoverInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AbilityMixinRecoverInfo buildPartial() {
        AbilityMixinRecoverInfo result = new AbilityMixinRecoverInfo(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(AbilityMixinRecoverInfo result) {
        if (massivePropListBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0)) {
            massivePropList_ = java.util.Collections.unmodifiableList(massivePropList_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.massivePropList_ = massivePropList_;
        } else {
          result.massivePropList_ = massivePropListBuilder_.build();
        }
      }

      private void buildPartial0(AbilityMixinRecoverInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.localId_ = localId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          dataList_.makeImmutable();
          result.dataList_ = dataList_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.isServerbuffModifier_ = isServerbuffModifier_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.breakoutSnapShot_ = breakoutSnapShotBuilder_ == null
              ? breakoutSnapShot_
              : breakoutSnapShotBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      private void buildPartialOneofs(AbilityMixinRecoverInfo result) {
        result.sourceCase_ = sourceCase_;
        result.source_ = this.source_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AbilityMixinRecoverInfo) {
          return mergeFrom((AbilityMixinRecoverInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AbilityMixinRecoverInfo other) {
        if (other == AbilityMixinRecoverInfo.getDefaultInstance()) return this;
        if (other.getLocalId() != 0) {
          setLocalId(other.getLocalId());
        }
        if (!other.dataList_.isEmpty()) {
          if (dataList_.isEmpty()) {
            dataList_ = other.dataList_;
            dataList_.makeImmutable();
            bitField0_ |= 0x00000008;
          } else {
            ensureDataListIsMutable();
            dataList_.addAll(other.dataList_);
          }
          onChanged();
        }
        if (other.getIsServerbuffModifier() != false) {
          setIsServerbuffModifier(other.getIsServerbuffModifier());
        }
        if (massivePropListBuilder_ == null) {
          if (!other.massivePropList_.isEmpty()) {
            if (massivePropList_.isEmpty()) {
              massivePropList_ = other.massivePropList_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureMassivePropListIsMutable();
              massivePropList_.addAll(other.massivePropList_);
            }
            onChanged();
          }
        } else {
          if (!other.massivePropList_.isEmpty()) {
            if (massivePropListBuilder_.isEmpty()) {
              massivePropListBuilder_.dispose();
              massivePropListBuilder_ = null;
              massivePropList_ = other.massivePropList_;
              bitField0_ = (bitField0_ & ~0x00000020);
              massivePropListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMassivePropListFieldBuilder() : null;
            } else {
              massivePropListBuilder_.addAllMessages(other.massivePropList_);
            }
          }
        }
        if (other.hasBreakoutSnapShot()) {
          mergeBreakoutSnapShot(other.getBreakoutSnapShot());
        }
        switch (other.getSourceCase()) {
          case INSTANCED_ABILITY_ID: {
            setInstancedAbilityId(other.getInstancedAbilityId());
            break;
          }
          case INSTANCED_MODIFIER_ID: {
            setInstancedModifierId(other.getInstancedModifierId());
            break;
          }
          case SOURCE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                source_ = input.readUInt32();
                sourceCase_ = 1;
                break;
              } // case 8
              case 16: {
                source_ = input.readUInt32();
                sourceCase_ = 2;
                break;
              } // case 16
              case 24: {
                localId_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                int v = input.readUInt32();
                ensureDataListIsMutable();
                dataList_.addInt(v);
                break;
              } // case 32
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureDataListIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  dataList_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              } // case 34
              case 40: {
                isServerbuffModifier_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                MassivePropSyncInfoOuterClass.MassivePropSyncInfo m =
                    input.readMessage(
                        MassivePropSyncInfoOuterClass.MassivePropSyncInfo.parser(),
                        extensionRegistry);
                if (massivePropListBuilder_ == null) {
                  ensureMassivePropListIsMutable();
                  massivePropList_.add(m);
                } else {
                  massivePropListBuilder_.addMessage(m);
                }
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getBreakoutSnapShotFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int sourceCase_ = 0;
      private Object source_;
      public SourceCase
          getSourceCase() {
        return SourceCase.forNumber(
            sourceCase_);
      }

      public Builder clearSource() {
        sourceCase_ = 0;
        source_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>uint32 instanced_ability_id = 1;</code>
       * @return Whether the instancedAbilityId field is set.
       */
      public boolean hasInstancedAbilityId() {
        return sourceCase_ == 1;
      }
      /**
       * <code>uint32 instanced_ability_id = 1;</code>
       * @return The instancedAbilityId.
       */
      public int getInstancedAbilityId() {
        if (sourceCase_ == 1) {
          return (Integer) source_;
        }
        return 0;
      }
      /**
       * <code>uint32 instanced_ability_id = 1;</code>
       * @param value The instancedAbilityId to set.
       * @return This builder for chaining.
       */
      public Builder setInstancedAbilityId(int value) {

        sourceCase_ = 1;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 instanced_ability_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstancedAbilityId() {
        if (sourceCase_ == 1) {
          sourceCase_ = 0;
          source_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>uint32 instanced_modifier_id = 2;</code>
       * @return Whether the instancedModifierId field is set.
       */
      public boolean hasInstancedModifierId() {
        return sourceCase_ == 2;
      }
      /**
       * <code>uint32 instanced_modifier_id = 2;</code>
       * @return The instancedModifierId.
       */
      public int getInstancedModifierId() {
        if (sourceCase_ == 2) {
          return (Integer) source_;
        }
        return 0;
      }
      /**
       * <code>uint32 instanced_modifier_id = 2;</code>
       * @param value The instancedModifierId to set.
       * @return This builder for chaining.
       */
      public Builder setInstancedModifierId(int value) {

        sourceCase_ = 2;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 instanced_modifier_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstancedModifierId() {
        if (sourceCase_ == 2) {
          sourceCase_ = 0;
          source_ = null;
          onChanged();
        }
        return this;
      }

      private int localId_ ;
      /**
       * <code>uint32 local_id = 3;</code>
       * @return The localId.
       */
      @Override
      public int getLocalId() {
        return localId_;
      }
      /**
       * <code>uint32 local_id = 3;</code>
       * @param value The localId to set.
       * @return This builder for chaining.
       */
      public Builder setLocalId(int value) {

        localId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 local_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        localId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList dataList_ = emptyIntList();
      private void ensureDataListIsMutable() {
        if (!dataList_.isModifiable()) {
          dataList_ = makeMutableCopy(dataList_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated uint32 data_list = 4;</code>
       * @return A list containing the dataList.
       */
      public java.util.List<Integer>
          getDataListList() {
        dataList_.makeImmutable();
        return dataList_;
      }
      /**
       * <code>repeated uint32 data_list = 4;</code>
       * @return The count of dataList.
       */
      public int getDataListCount() {
        return dataList_.size();
      }
      /**
       * <code>repeated uint32 data_list = 4;</code>
       * @param index The index of the element to return.
       * @return The dataList at the given index.
       */
      public int getDataList(int index) {
        return dataList_.getInt(index);
      }
      /**
       * <code>repeated uint32 data_list = 4;</code>
       * @param index The index to set the value at.
       * @param value The dataList to set.
       * @return This builder for chaining.
       */
      public Builder setDataList(
          int index, int value) {

        ensureDataListIsMutable();
        dataList_.setInt(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 data_list = 4;</code>
       * @param value The dataList to add.
       * @return This builder for chaining.
       */
      public Builder addDataList(int value) {

        ensureDataListIsMutable();
        dataList_.addInt(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 data_list = 4;</code>
       * @param values The dataList to add.
       * @return This builder for chaining.
       */
      public Builder addAllDataList(
          Iterable<? extends Integer> values) {
        ensureDataListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataList_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 data_list = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataList() {
        dataList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private boolean isServerbuffModifier_ ;
      /**
       * <code>bool is_serverbuff_modifier = 5;</code>
       * @return The isServerbuffModifier.
       */
      @Override
      public boolean getIsServerbuffModifier() {
        return isServerbuffModifier_;
      }
      /**
       * <code>bool is_serverbuff_modifier = 5;</code>
       * @param value The isServerbuffModifier to set.
       * @return This builder for chaining.
       */
      public Builder setIsServerbuffModifier(boolean value) {

        isServerbuffModifier_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_serverbuff_modifier = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsServerbuffModifier() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isServerbuffModifier_ = false;
        onChanged();
        return this;
      }

      private java.util.List<MassivePropSyncInfoOuterClass.MassivePropSyncInfo> massivePropList_ =
        java.util.Collections.emptyList();
      private void ensureMassivePropListIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          massivePropList_ = new java.util.ArrayList<MassivePropSyncInfoOuterClass.MassivePropSyncInfo>(massivePropList_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          MassivePropSyncInfoOuterClass.MassivePropSyncInfo, MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder, MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder> massivePropListBuilder_;

      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public java.util.List<MassivePropSyncInfoOuterClass.MassivePropSyncInfo> getMassivePropListList() {
        if (massivePropListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(massivePropList_);
        } else {
          return massivePropListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public int getMassivePropListCount() {
        if (massivePropListBuilder_ == null) {
          return massivePropList_.size();
        } else {
          return massivePropListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public MassivePropSyncInfoOuterClass.MassivePropSyncInfo getMassivePropList(int index) {
        if (massivePropListBuilder_ == null) {
          return massivePropList_.get(index);
        } else {
          return massivePropListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder setMassivePropList(
          int index, MassivePropSyncInfoOuterClass.MassivePropSyncInfo value) {
        if (massivePropListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMassivePropListIsMutable();
          massivePropList_.set(index, value);
          onChanged();
        } else {
          massivePropListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder setMassivePropList(
          int index, MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder builderForValue) {
        if (massivePropListBuilder_ == null) {
          ensureMassivePropListIsMutable();
          massivePropList_.set(index, builderForValue.build());
          onChanged();
        } else {
          massivePropListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder addMassivePropList(MassivePropSyncInfoOuterClass.MassivePropSyncInfo value) {
        if (massivePropListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMassivePropListIsMutable();
          massivePropList_.add(value);
          onChanged();
        } else {
          massivePropListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder addMassivePropList(
          int index, MassivePropSyncInfoOuterClass.MassivePropSyncInfo value) {
        if (massivePropListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMassivePropListIsMutable();
          massivePropList_.add(index, value);
          onChanged();
        } else {
          massivePropListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder addMassivePropList(
          MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder builderForValue) {
        if (massivePropListBuilder_ == null) {
          ensureMassivePropListIsMutable();
          massivePropList_.add(builderForValue.build());
          onChanged();
        } else {
          massivePropListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder addMassivePropList(
          int index, MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder builderForValue) {
        if (massivePropListBuilder_ == null) {
          ensureMassivePropListIsMutable();
          massivePropList_.add(index, builderForValue.build());
          onChanged();
        } else {
          massivePropListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder addAllMassivePropList(
          Iterable<? extends MassivePropSyncInfoOuterClass.MassivePropSyncInfo> values) {
        if (massivePropListBuilder_ == null) {
          ensureMassivePropListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, massivePropList_);
          onChanged();
        } else {
          massivePropListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder clearMassivePropList() {
        if (massivePropListBuilder_ == null) {
          massivePropList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          massivePropListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public Builder removeMassivePropList(int index) {
        if (massivePropListBuilder_ == null) {
          ensureMassivePropListIsMutable();
          massivePropList_.remove(index);
          onChanged();
        } else {
          massivePropListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder getMassivePropListBuilder(
          int index) {
        return getMassivePropListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder getMassivePropListOrBuilder(
          int index) {
        if (massivePropListBuilder_ == null) {
          return massivePropList_.get(index);  } else {
          return massivePropListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public java.util.List<? extends MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder>
           getMassivePropListOrBuilderList() {
        if (massivePropListBuilder_ != null) {
          return massivePropListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(massivePropList_);
        }
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder addMassivePropListBuilder() {
        return getMassivePropListFieldBuilder().addBuilder(
            MassivePropSyncInfoOuterClass.MassivePropSyncInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder addMassivePropListBuilder(
          int index) {
        return getMassivePropListFieldBuilder().addBuilder(
            index, MassivePropSyncInfoOuterClass.MassivePropSyncInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .MassivePropSyncInfo massive_prop_list = 6;</code>
       */
      public java.util.List<MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder>
           getMassivePropListBuilderList() {
        return getMassivePropListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          MassivePropSyncInfoOuterClass.MassivePropSyncInfo, MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder, MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder>
          getMassivePropListFieldBuilder() {
        if (massivePropListBuilder_ == null) {
          massivePropListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              MassivePropSyncInfoOuterClass.MassivePropSyncInfo, MassivePropSyncInfoOuterClass.MassivePropSyncInfo.Builder, MassivePropSyncInfoOuterClass.MassivePropSyncInfoOrBuilder>(
                  massivePropList_,
                  ((bitField0_ & 0x00000020) != 0),
                  getParentForChildren(),
                  isClean());
          massivePropList_ = null;
        }
        return massivePropListBuilder_;
      }

      private BreakoutSnapShotOuterClass.BreakoutSnapShot breakoutSnapShot_;
      private com.google.protobuf.SingleFieldBuilder<
          BreakoutSnapShotOuterClass.BreakoutSnapShot, BreakoutSnapShotOuterClass.BreakoutSnapShot.Builder, BreakoutSnapShotOuterClass.BreakoutSnapShotOrBuilder> breakoutSnapShotBuilder_;
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       * @return Whether the breakoutSnapShot field is set.
       */
      public boolean hasBreakoutSnapShot() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       * @return The breakoutSnapShot.
       */
      public BreakoutSnapShotOuterClass.BreakoutSnapShot getBreakoutSnapShot() {
        if (breakoutSnapShotBuilder_ == null) {
          return breakoutSnapShot_ == null ? BreakoutSnapShotOuterClass.BreakoutSnapShot.getDefaultInstance() : breakoutSnapShot_;
        } else {
          return breakoutSnapShotBuilder_.getMessage();
        }
      }
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       */
      public Builder setBreakoutSnapShot(BreakoutSnapShotOuterClass.BreakoutSnapShot value) {
        if (breakoutSnapShotBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          breakoutSnapShot_ = value;
        } else {
          breakoutSnapShotBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       */
      public Builder setBreakoutSnapShot(
          BreakoutSnapShotOuterClass.BreakoutSnapShot.Builder builderForValue) {
        if (breakoutSnapShotBuilder_ == null) {
          breakoutSnapShot_ = builderForValue.build();
        } else {
          breakoutSnapShotBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       */
      public Builder mergeBreakoutSnapShot(BreakoutSnapShotOuterClass.BreakoutSnapShot value) {
        if (breakoutSnapShotBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            breakoutSnapShot_ != null &&
            breakoutSnapShot_ != BreakoutSnapShotOuterClass.BreakoutSnapShot.getDefaultInstance()) {
            getBreakoutSnapShotBuilder().mergeFrom(value);
          } else {
            breakoutSnapShot_ = value;
          }
        } else {
          breakoutSnapShotBuilder_.mergeFrom(value);
        }
        if (breakoutSnapShot_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       */
      public Builder clearBreakoutSnapShot() {
        bitField0_ = (bitField0_ & ~0x00000040);
        breakoutSnapShot_ = null;
        if (breakoutSnapShotBuilder_ != null) {
          breakoutSnapShotBuilder_.dispose();
          breakoutSnapShotBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       */
      public BreakoutSnapShotOuterClass.BreakoutSnapShot.Builder getBreakoutSnapShotBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getBreakoutSnapShotFieldBuilder().getBuilder();
      }
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       */
      public BreakoutSnapShotOuterClass.BreakoutSnapShotOrBuilder getBreakoutSnapShotOrBuilder() {
        if (breakoutSnapShotBuilder_ != null) {
          return breakoutSnapShotBuilder_.getMessageOrBuilder();
        } else {
          return breakoutSnapShot_ == null ?
              BreakoutSnapShotOuterClass.BreakoutSnapShot.getDefaultInstance() : breakoutSnapShot_;
        }
      }
      /**
       * <code>.BreakoutSnapShot breakout_snap_shot = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          BreakoutSnapShotOuterClass.BreakoutSnapShot, BreakoutSnapShotOuterClass.BreakoutSnapShot.Builder, BreakoutSnapShotOuterClass.BreakoutSnapShotOrBuilder>
          getBreakoutSnapShotFieldBuilder() {
        if (breakoutSnapShotBuilder_ == null) {
          breakoutSnapShotBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              BreakoutSnapShotOuterClass.BreakoutSnapShot, BreakoutSnapShotOuterClass.BreakoutSnapShot.Builder, BreakoutSnapShotOuterClass.BreakoutSnapShotOrBuilder>(
                  getBreakoutSnapShot(),
                  getParentForChildren(),
                  isClean());
          breakoutSnapShot_ = null;
        }
        return breakoutSnapShotBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:AbilityMixinRecoverInfo)
    }

    // @@protoc_insertion_point(class_scope:AbilityMixinRecoverInfo)
    private static final AbilityMixinRecoverInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AbilityMixinRecoverInfo();
    }

    public static AbilityMixinRecoverInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AbilityMixinRecoverInfo>
        PARSER = new com.google.protobuf.AbstractParser<AbilityMixinRecoverInfo>() {
      @Override
      public AbilityMixinRecoverInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AbilityMixinRecoverInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AbilityMixinRecoverInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public AbilityMixinRecoverInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AbilityMixinRecoverInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AbilityMixinRecoverInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035AbilityMixinRecoverInfo.proto\032\031Massive" +
      "PropSyncInfo.proto\032\026BreakoutSnapShot.pro" +
      "to\"\211\002\n\027AbilityMixinRecoverInfo\022\036\n\024instan" +
      "ced_ability_id\030\001 \001(\rH\000\022\037\n\025instanced_modi" +
      "fier_id\030\002 \001(\rH\000\022\020\n\010local_id\030\003 \001(\r\022\021\n\tdat" +
      "a_list\030\004 \003(\r\022\036\n\026is_serverbuff_modifier\030\005" +
      " \001(\010\022/\n\021massive_prop_list\030\006 \003(\0132\024.Massiv" +
      "ePropSyncInfo\022-\n\022breakout_snap_shot\030\007 \001(" +
      "\0132\021.BreakoutSnapShotB\010\n\006SourceB\032\n\030io.irm" +
      "insul.common.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MassivePropSyncInfoOuterClass.getDescriptor(),
          BreakoutSnapShotOuterClass.getDescriptor(),
        });
    internal_static_AbilityMixinRecoverInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AbilityMixinRecoverInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AbilityMixinRecoverInfo_descriptor,
        new String[] { "InstancedAbilityId", "InstancedModifierId", "LocalId", "DataList", "IsServerbuffModifier", "MassivePropList", "BreakoutSnapShot", "Source", });
    descriptor.resolveAllFeaturesImmutable();
    MassivePropSyncInfoOuterClass.getDescriptor();
    BreakoutSnapShotOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
