// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BossChestInfo.proto
// Protobuf Java Version: 4.27.2

package io.irminsul.common.proto;

public final class BossChestInfoOuterClass {
  private BossChestInfoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      BossChestInfoOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BossChestInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BossChestInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 monster_config_id = 1;</code>
     * @return The monsterConfigId.
     */
    int getMonsterConfigId();

    /**
     * <code>uint32 resin = 2;</code>
     * @return The resin.
     */
    int getResin();

    /**
     * <code>repeated uint32 remain_uid_list = 3;</code>
     * @return A list containing the remainUidList.
     */
    java.util.List<Integer> getRemainUidListList();
    /**
     * <code>repeated uint32 remain_uid_list = 3;</code>
     * @return The count of remainUidList.
     */
    int getRemainUidListCount();
    /**
     * <code>repeated uint32 remain_uid_list = 3;</code>
     * @param index The index of the element to return.
     * @return The remainUidList at the given index.
     */
    int getRemainUidList(int index);

    /**
     * <code>repeated uint32 qualify_uid_list = 4;</code>
     * @return A list containing the qualifyUidList.
     */
    java.util.List<Integer> getQualifyUidListList();
    /**
     * <code>repeated uint32 qualify_uid_list = 4;</code>
     * @return The count of qualifyUidList.
     */
    int getQualifyUidListCount();
    /**
     * <code>repeated uint32 qualify_uid_list = 4;</code>
     * @param index The index of the element to return.
     * @return The qualifyUidList at the given index.
     */
    int getQualifyUidList(int index);

    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    int getUidDiscountMapCount();
    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    boolean containsUidDiscountMap(
        int key);
    /**
     * Use {@link #getUidDiscountMapMap()} instead.
     */
    @Deprecated
    java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo>
    getUidDiscountMap();
    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo>
    getUidDiscountMapMap();
    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    /* nullable */
WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo getUidDiscountMapOrDefault(
        int key,
        /* nullable */
WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo defaultValue);
    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo getUidDiscountMapOrThrow(
        int key);
  }
  /**
   * <pre>
   * Obf: CBKAOHFJIND
   * </pre>
   *
   * Protobuf type {@code BossChestInfo}
   */
  public static final class BossChestInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BossChestInfo)
      BossChestInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        BossChestInfo.class.getName());
    }
    // Use BossChestInfo.newBuilder() to construct.
    private BossChestInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BossChestInfo() {
      remainUidList_ = emptyIntList();
      qualifyUidList_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BossChestInfoOuterClass.internal_static_BossChestInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetUidDiscountMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BossChestInfoOuterClass.internal_static_BossChestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BossChestInfo.class, Builder.class);
    }

    public static final int MONSTER_CONFIG_ID_FIELD_NUMBER = 1;
    private int monsterConfigId_ = 0;
    /**
     * <code>uint32 monster_config_id = 1;</code>
     * @return The monsterConfigId.
     */
    @Override
    public int getMonsterConfigId() {
      return monsterConfigId_;
    }

    public static final int RESIN_FIELD_NUMBER = 2;
    private int resin_ = 0;
    /**
     * <code>uint32 resin = 2;</code>
     * @return The resin.
     */
    @Override
    public int getResin() {
      return resin_;
    }

    public static final int REMAIN_UID_LIST_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList remainUidList_ =
        emptyIntList();
    /**
     * <code>repeated uint32 remain_uid_list = 3;</code>
     * @return A list containing the remainUidList.
     */
    @Override
    public java.util.List<Integer>
        getRemainUidListList() {
      return remainUidList_;
    }
    /**
     * <code>repeated uint32 remain_uid_list = 3;</code>
     * @return The count of remainUidList.
     */
    public int getRemainUidListCount() {
      return remainUidList_.size();
    }
    /**
     * <code>repeated uint32 remain_uid_list = 3;</code>
     * @param index The index of the element to return.
     * @return The remainUidList at the given index.
     */
    public int getRemainUidList(int index) {
      return remainUidList_.getInt(index);
    }
    private int remainUidListMemoizedSerializedSize = -1;

    public static final int QUALIFY_UID_LIST_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList qualifyUidList_ =
        emptyIntList();
    /**
     * <code>repeated uint32 qualify_uid_list = 4;</code>
     * @return A list containing the qualifyUidList.
     */
    @Override
    public java.util.List<Integer>
        getQualifyUidListList() {
      return qualifyUidList_;
    }
    /**
     * <code>repeated uint32 qualify_uid_list = 4;</code>
     * @return The count of qualifyUidList.
     */
    public int getQualifyUidListCount() {
      return qualifyUidList_.size();
    }
    /**
     * <code>repeated uint32 qualify_uid_list = 4;</code>
     * @param index The index of the element to return.
     * @return The qualifyUidList at the given index.
     */
    public int getQualifyUidList(int index) {
      return qualifyUidList_.getInt(index);
    }
    private int qualifyUidListMemoizedSerializedSize = -1;

    public static final int UID_DISCOUNT_MAP_FIELD_NUMBER = 5;
    private static final class UidDiscountMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo>newDefaultInstance(
                  BossChestInfoOuterClass.internal_static_BossChestInfo_UidDiscountMapEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> uidDiscountMap_;
    private com.google.protobuf.MapField<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo>
    internalGetUidDiscountMap() {
      if (uidDiscountMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UidDiscountMapDefaultEntryHolder.defaultEntry);
      }
      return uidDiscountMap_;
    }
    public int getUidDiscountMapCount() {
      return internalGetUidDiscountMap().getMap().size();
    }
    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    @Override
    public boolean containsUidDiscountMap(
        int key) {

      return internalGetUidDiscountMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUidDiscountMapMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> getUidDiscountMap() {
      return getUidDiscountMapMap();
    }
    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    @Override
    public java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> getUidDiscountMapMap() {
      return internalGetUidDiscountMap().getMap();
    }
    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    @Override
    public /* nullable */
WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo getUidDiscountMapOrDefault(
        int key,
        /* nullable */
WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo defaultValue) {

      java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> map =
          internalGetUidDiscountMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
     */
    @Override
    public WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo getUidDiscountMapOrThrow(
        int key) {

      java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> map =
          internalGetUidDiscountMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (monsterConfigId_ != 0) {
        output.writeUInt32(1, monsterConfigId_);
      }
      if (resin_ != 0) {
        output.writeUInt32(2, resin_);
      }
      if (getRemainUidListList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(remainUidListMemoizedSerializedSize);
      }
      for (int i = 0; i < remainUidList_.size(); i++) {
        output.writeUInt32NoTag(remainUidList_.getInt(i));
      }
      if (getQualifyUidListList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(qualifyUidListMemoizedSerializedSize);
      }
      for (int i = 0; i < qualifyUidList_.size(); i++) {
        output.writeUInt32NoTag(qualifyUidList_.getInt(i));
      }
      com.google.protobuf.GeneratedMessage
        .serializeIntegerMapTo(
          output,
          internalGetUidDiscountMap(),
          UidDiscountMapDefaultEntryHolder.defaultEntry,
          5);
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (monsterConfigId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, monsterConfigId_);
      }
      if (resin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, resin_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < remainUidList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(remainUidList_.getInt(i));
        }
        size += dataSize;
        if (!getRemainUidListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        remainUidListMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < qualifyUidList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(qualifyUidList_.getInt(i));
        }
        size += dataSize;
        if (!getQualifyUidListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        qualifyUidListMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> entry
           : internalGetUidDiscountMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo>
        uidDiscountMap__ = UidDiscountMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, uidDiscountMap__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BossChestInfo)) {
        return super.equals(obj);
      }
      BossChestInfo other = (BossChestInfo) obj;

      if (getMonsterConfigId()
          != other.getMonsterConfigId()) return false;
      if (getResin()
          != other.getResin()) return false;
      if (!getRemainUidListList()
          .equals(other.getRemainUidListList())) return false;
      if (!getQualifyUidListList()
          .equals(other.getQualifyUidListList())) return false;
      if (!internalGetUidDiscountMap().equals(
          other.internalGetUidDiscountMap())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MONSTER_CONFIG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMonsterConfigId();
      hash = (37 * hash) + RESIN_FIELD_NUMBER;
      hash = (53 * hash) + getResin();
      if (getRemainUidListCount() > 0) {
        hash = (37 * hash) + REMAIN_UID_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getRemainUidListList().hashCode();
      }
      if (getQualifyUidListCount() > 0) {
        hash = (37 * hash) + QUALIFY_UID_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getQualifyUidListList().hashCode();
      }
      if (!internalGetUidDiscountMap().getMap().isEmpty()) {
        hash = (37 * hash) + UID_DISCOUNT_MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetUidDiscountMap().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BossChestInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BossChestInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BossChestInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BossChestInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BossChestInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BossChestInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BossChestInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static BossChestInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static BossChestInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static BossChestInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BossChestInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static BossChestInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BossChestInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Obf: CBKAOHFJIND
     * </pre>
     *
     * Protobuf type {@code BossChestInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BossChestInfo)
        BossChestInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BossChestInfoOuterClass.internal_static_BossChestInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 5:
            return internalGetUidDiscountMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableUidDiscountMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BossChestInfoOuterClass.internal_static_BossChestInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BossChestInfo.class, Builder.class);
      }

      // Construct using io.irminsul.common.proto.BossChestInfoOuterClass.BossChestInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        monsterConfigId_ = 0;
        resin_ = 0;
        remainUidList_ = emptyIntList();
        qualifyUidList_ = emptyIntList();
        internalGetMutableUidDiscountMap().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BossChestInfoOuterClass.internal_static_BossChestInfo_descriptor;
      }

      @Override
      public BossChestInfo getDefaultInstanceForType() {
        return BossChestInfo.getDefaultInstance();
      }

      @Override
      public BossChestInfo build() {
        BossChestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BossChestInfo buildPartial() {
        BossChestInfo result = new BossChestInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(BossChestInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.monsterConfigId_ = monsterConfigId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.resin_ = resin_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          remainUidList_.makeImmutable();
          result.remainUidList_ = remainUidList_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          qualifyUidList_.makeImmutable();
          result.qualifyUidList_ = qualifyUidList_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.uidDiscountMap_ = internalGetUidDiscountMap().build(UidDiscountMapDefaultEntryHolder.defaultEntry);
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BossChestInfo) {
          return mergeFrom((BossChestInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BossChestInfo other) {
        if (other == BossChestInfo.getDefaultInstance()) return this;
        if (other.getMonsterConfigId() != 0) {
          setMonsterConfigId(other.getMonsterConfigId());
        }
        if (other.getResin() != 0) {
          setResin(other.getResin());
        }
        if (!other.remainUidList_.isEmpty()) {
          if (remainUidList_.isEmpty()) {
            remainUidList_ = other.remainUidList_;
            remainUidList_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureRemainUidListIsMutable();
            remainUidList_.addAll(other.remainUidList_);
          }
          onChanged();
        }
        if (!other.qualifyUidList_.isEmpty()) {
          if (qualifyUidList_.isEmpty()) {
            qualifyUidList_ = other.qualifyUidList_;
            qualifyUidList_.makeImmutable();
            bitField0_ |= 0x00000008;
          } else {
            ensureQualifyUidListIsMutable();
            qualifyUidList_.addAll(other.qualifyUidList_);
          }
          onChanged();
        }
        internalGetMutableUidDiscountMap().mergeFrom(
            other.internalGetUidDiscountMap());
        bitField0_ |= 0x00000010;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                monsterConfigId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                resin_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                int v = input.readUInt32();
                ensureRemainUidListIsMutable();
                remainUidList_.addInt(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureRemainUidListIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  remainUidList_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 32: {
                int v = input.readUInt32();
                ensureQualifyUidListIsMutable();
                qualifyUidList_.addInt(v);
                break;
              } // case 32
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureQualifyUidListIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  qualifyUidList_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              } // case 34
              case 42: {
                com.google.protobuf.MapEntry<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo>
                uidDiscountMap__ = input.readMessage(
                    UidDiscountMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableUidDiscountMap().ensureBuilderMap().put(
                    uidDiscountMap__.getKey(), uidDiscountMap__.getValue());
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int monsterConfigId_ ;
      /**
       * <code>uint32 monster_config_id = 1;</code>
       * @return The monsterConfigId.
       */
      @Override
      public int getMonsterConfigId() {
        return monsterConfigId_;
      }
      /**
       * <code>uint32 monster_config_id = 1;</code>
       * @param value The monsterConfigId to set.
       * @return This builder for chaining.
       */
      public Builder setMonsterConfigId(int value) {

        monsterConfigId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 monster_config_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonsterConfigId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        monsterConfigId_ = 0;
        onChanged();
        return this;
      }

      private int resin_ ;
      /**
       * <code>uint32 resin = 2;</code>
       * @return The resin.
       */
      @Override
      public int getResin() {
        return resin_;
      }
      /**
       * <code>uint32 resin = 2;</code>
       * @param value The resin to set.
       * @return This builder for chaining.
       */
      public Builder setResin(int value) {

        resin_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 resin = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resin_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList remainUidList_ = emptyIntList();
      private void ensureRemainUidListIsMutable() {
        if (!remainUidList_.isModifiable()) {
          remainUidList_ = makeMutableCopy(remainUidList_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated uint32 remain_uid_list = 3;</code>
       * @return A list containing the remainUidList.
       */
      public java.util.List<Integer>
          getRemainUidListList() {
        remainUidList_.makeImmutable();
        return remainUidList_;
      }
      /**
       * <code>repeated uint32 remain_uid_list = 3;</code>
       * @return The count of remainUidList.
       */
      public int getRemainUidListCount() {
        return remainUidList_.size();
      }
      /**
       * <code>repeated uint32 remain_uid_list = 3;</code>
       * @param index The index of the element to return.
       * @return The remainUidList at the given index.
       */
      public int getRemainUidList(int index) {
        return remainUidList_.getInt(index);
      }
      /**
       * <code>repeated uint32 remain_uid_list = 3;</code>
       * @param index The index to set the value at.
       * @param value The remainUidList to set.
       * @return This builder for chaining.
       */
      public Builder setRemainUidList(
          int index, int value) {

        ensureRemainUidListIsMutable();
        remainUidList_.setInt(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 remain_uid_list = 3;</code>
       * @param value The remainUidList to add.
       * @return This builder for chaining.
       */
      public Builder addRemainUidList(int value) {

        ensureRemainUidListIsMutable();
        remainUidList_.addInt(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 remain_uid_list = 3;</code>
       * @param values The remainUidList to add.
       * @return This builder for chaining.
       */
      public Builder addAllRemainUidList(
          Iterable<? extends Integer> values) {
        ensureRemainUidListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, remainUidList_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 remain_uid_list = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemainUidList() {
        remainUidList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList qualifyUidList_ = emptyIntList();
      private void ensureQualifyUidListIsMutable() {
        if (!qualifyUidList_.isModifiable()) {
          qualifyUidList_ = makeMutableCopy(qualifyUidList_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated uint32 qualify_uid_list = 4;</code>
       * @return A list containing the qualifyUidList.
       */
      public java.util.List<Integer>
          getQualifyUidListList() {
        qualifyUidList_.makeImmutable();
        return qualifyUidList_;
      }
      /**
       * <code>repeated uint32 qualify_uid_list = 4;</code>
       * @return The count of qualifyUidList.
       */
      public int getQualifyUidListCount() {
        return qualifyUidList_.size();
      }
      /**
       * <code>repeated uint32 qualify_uid_list = 4;</code>
       * @param index The index of the element to return.
       * @return The qualifyUidList at the given index.
       */
      public int getQualifyUidList(int index) {
        return qualifyUidList_.getInt(index);
      }
      /**
       * <code>repeated uint32 qualify_uid_list = 4;</code>
       * @param index The index to set the value at.
       * @param value The qualifyUidList to set.
       * @return This builder for chaining.
       */
      public Builder setQualifyUidList(
          int index, int value) {

        ensureQualifyUidListIsMutable();
        qualifyUidList_.setInt(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 qualify_uid_list = 4;</code>
       * @param value The qualifyUidList to add.
       * @return This builder for chaining.
       */
      public Builder addQualifyUidList(int value) {

        ensureQualifyUidListIsMutable();
        qualifyUidList_.addInt(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 qualify_uid_list = 4;</code>
       * @param values The qualifyUidList to add.
       * @return This builder for chaining.
       */
      public Builder addAllQualifyUidList(
          Iterable<? extends Integer> values) {
        ensureQualifyUidListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, qualifyUidList_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 qualify_uid_list = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearQualifyUidList() {
        qualifyUidList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private static final class UidDiscountMapConverter implements com.google.protobuf.MapFieldBuilder.Converter<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> {
        @Override
        public WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo build(WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder val) {
          if (val instanceof WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo) { return (WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo) val; }
          return ((WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo.Builder) val).build();
        }

        @Override
        public com.google.protobuf.MapEntry<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> defaultEntry() {
          return UidDiscountMapDefaultEntryHolder.defaultEntry;
        }
      };
      private static final UidDiscountMapConverter uidDiscountMapConverter = new UidDiscountMapConverter();

      private com.google.protobuf.MapFieldBuilder<
          Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo.Builder> uidDiscountMap_;
      private com.google.protobuf.MapFieldBuilder<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo.Builder>
          internalGetUidDiscountMap() {
        if (uidDiscountMap_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(uidDiscountMapConverter);
        }
        return uidDiscountMap_;
      }
      private com.google.protobuf.MapFieldBuilder<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo.Builder>
          internalGetMutableUidDiscountMap() {
        if (uidDiscountMap_ == null) {
          uidDiscountMap_ = new com.google.protobuf.MapFieldBuilder<>(uidDiscountMapConverter);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return uidDiscountMap_;
      }
      public int getUidDiscountMapCount() {
        return internalGetUidDiscountMap().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
       */
      @Override
      public boolean containsUidDiscountMap(
          int key) {

        return internalGetUidDiscountMap().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getUidDiscountMapMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> getUidDiscountMap() {
        return getUidDiscountMapMap();
      }
      /**
       * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
       */
      @Override
      public java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> getUidDiscountMapMap() {
        return internalGetUidDiscountMap().getImmutableMap();
      }
      /**
       * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
       */
      @Override
      public /* nullable */
WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo getUidDiscountMapOrDefault(
          int key,
          /* nullable */
WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo defaultValue) {

        java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder> map = internalGetMutableUidDiscountMap().ensureBuilderMap();
        return map.containsKey(key) ? uidDiscountMapConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
       */
      @Override
      public WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo getUidDiscountMapOrThrow(
          int key) {

        java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder> map = internalGetMutableUidDiscountMap().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return uidDiscountMapConverter.build(map.get(key));
      }
      public Builder clearUidDiscountMap() {
        bitField0_ = (bitField0_ & ~0x00000010);
        internalGetMutableUidDiscountMap().clear();
        return this;
      }
      /**
       * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
       */
      public Builder removeUidDiscountMap(
          int key) {

        internalGetMutableUidDiscountMap().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo>
          getMutableUidDiscountMap() {
        bitField0_ |= 0x00000010;
        return internalGetMutableUidDiscountMap().ensureMessageMap();
      }
      /**
       * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
       */
      public Builder putUidDiscountMap(
          int key,
          WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo value) {

        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableUidDiscountMap().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
       */
      public Builder putAllUidDiscountMap(
          java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> values) {
        for (java.util.Map.Entry<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableUidDiscountMap().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>map&lt;uint32, .WeeklyBossResinDiscountInfo&gt; uid_discount_map = 5;</code>
       */
      public WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo.Builder putUidDiscountMapBuilderIfAbsent(
          int key) {
        java.util.Map<Integer, WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder> builderMap = internalGetMutableUidDiscountMap().ensureBuilderMap();
        WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfoOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo) {
          entry = ((WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (WeeklyBossResinDiscountInfoOuterClass.WeeklyBossResinDiscountInfo.Builder) entry;
      }

      // @@protoc_insertion_point(builder_scope:BossChestInfo)
    }

    // @@protoc_insertion_point(class_scope:BossChestInfo)
    private static final BossChestInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BossChestInfo();
    }

    public static BossChestInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BossChestInfo>
        PARSER = new com.google.protobuf.AbstractParser<BossChestInfo>() {
      @Override
      public BossChestInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BossChestInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BossChestInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public BossChestInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BossChestInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BossChestInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BossChestInfo_UidDiscountMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BossChestInfo_UidDiscountMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023BossChestInfo.proto\032!WeeklyBossResinDi" +
      "scountInfo.proto\"\377\001\n\rBossChestInfo\022\031\n\021mo" +
      "nster_config_id\030\001 \001(\r\022\r\n\005resin\030\002 \001(\r\022\027\n\017" +
      "remain_uid_list\030\003 \003(\r\022\030\n\020qualify_uid_lis" +
      "t\030\004 \003(\r\022<\n\020uid_discount_map\030\005 \003(\0132\".Boss" +
      "ChestInfo.UidDiscountMapEntry\032S\n\023UidDisc" +
      "ountMapEntry\022\013\n\003key\030\001 \001(\r\022+\n\005value\030\002 \001(\013" +
      "2\034.WeeklyBossResinDiscountInfo:\0028\001B\032\n\030io" +
      ".irminsul.common.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          WeeklyBossResinDiscountInfoOuterClass.getDescriptor(),
        });
    internal_static_BossChestInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BossChestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BossChestInfo_descriptor,
        new String[] { "MonsterConfigId", "Resin", "RemainUidList", "QualifyUidList", "UidDiscountMap", });
    internal_static_BossChestInfo_UidDiscountMapEntry_descriptor =
      internal_static_BossChestInfo_descriptor.getNestedTypes().get(0);
    internal_static_BossChestInfo_UidDiscountMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BossChestInfo_UidDiscountMapEntry_descriptor,
        new String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    WeeklyBossResinDiscountInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
