// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: EntityEnvironmentInfo.proto
// Protobuf Java Version: 4.27.2

package io.irminsul.common.proto;

public final class EntityEnvironmentInfoOuterClass {
  private EntityEnvironmentInfoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      EntityEnvironmentInfoOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EntityEnvironmentInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EntityEnvironmentInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 json_climate_type = 1;</code>
     * @return The jsonClimateType.
     */
    int getJsonClimateType();

    /**
     * <code>uint32 climate_area_id = 2;</code>
     * @return The climateAreaId.
     */
    int getClimateAreaId();
  }
  /**
   * <pre>
   * Obf: FDGMLNKHDKB
   * </pre>
   *
   * Protobuf type {@code EntityEnvironmentInfo}
   */
  public static final class EntityEnvironmentInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EntityEnvironmentInfo)
      EntityEnvironmentInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        EntityEnvironmentInfo.class.getName());
    }
    // Use EntityEnvironmentInfo.newBuilder() to construct.
    private EntityEnvironmentInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EntityEnvironmentInfo() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EntityEnvironmentInfoOuterClass.internal_static_EntityEnvironmentInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EntityEnvironmentInfoOuterClass.internal_static_EntityEnvironmentInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EntityEnvironmentInfo.class, Builder.class);
    }

    public static final int JSON_CLIMATE_TYPE_FIELD_NUMBER = 1;
    private int jsonClimateType_ = 0;
    /**
     * <code>uint32 json_climate_type = 1;</code>
     * @return The jsonClimateType.
     */
    @Override
    public int getJsonClimateType() {
      return jsonClimateType_;
    }

    public static final int CLIMATE_AREA_ID_FIELD_NUMBER = 2;
    private int climateAreaId_ = 0;
    /**
     * <code>uint32 climate_area_id = 2;</code>
     * @return The climateAreaId.
     */
    @Override
    public int getClimateAreaId() {
      return climateAreaId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (jsonClimateType_ != 0) {
        output.writeUInt32(1, jsonClimateType_);
      }
      if (climateAreaId_ != 0) {
        output.writeUInt32(2, climateAreaId_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (jsonClimateType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, jsonClimateType_);
      }
      if (climateAreaId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, climateAreaId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EntityEnvironmentInfo)) {
        return super.equals(obj);
      }
      EntityEnvironmentInfo other = (EntityEnvironmentInfo) obj;

      if (getJsonClimateType()
          != other.getJsonClimateType()) return false;
      if (getClimateAreaId()
          != other.getClimateAreaId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSON_CLIMATE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getJsonClimateType();
      hash = (37 * hash) + CLIMATE_AREA_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClimateAreaId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EntityEnvironmentInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityEnvironmentInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityEnvironmentInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityEnvironmentInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityEnvironmentInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityEnvironmentInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityEnvironmentInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EntityEnvironmentInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static EntityEnvironmentInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static EntityEnvironmentInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EntityEnvironmentInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EntityEnvironmentInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EntityEnvironmentInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Obf: FDGMLNKHDKB
     * </pre>
     *
     * Protobuf type {@code EntityEnvironmentInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EntityEnvironmentInfo)
        EntityEnvironmentInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EntityEnvironmentInfoOuterClass.internal_static_EntityEnvironmentInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EntityEnvironmentInfoOuterClass.internal_static_EntityEnvironmentInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EntityEnvironmentInfo.class, Builder.class);
      }

      // Construct using io.irminsul.common.proto.EntityEnvironmentInfoOuterClass.EntityEnvironmentInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        jsonClimateType_ = 0;
        climateAreaId_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EntityEnvironmentInfoOuterClass.internal_static_EntityEnvironmentInfo_descriptor;
      }

      @Override
      public EntityEnvironmentInfo getDefaultInstanceForType() {
        return EntityEnvironmentInfo.getDefaultInstance();
      }

      @Override
      public EntityEnvironmentInfo build() {
        EntityEnvironmentInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EntityEnvironmentInfo buildPartial() {
        EntityEnvironmentInfo result = new EntityEnvironmentInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(EntityEnvironmentInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.jsonClimateType_ = jsonClimateType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.climateAreaId_ = climateAreaId_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EntityEnvironmentInfo) {
          return mergeFrom((EntityEnvironmentInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EntityEnvironmentInfo other) {
        if (other == EntityEnvironmentInfo.getDefaultInstance()) return this;
        if (other.getJsonClimateType() != 0) {
          setJsonClimateType(other.getJsonClimateType());
        }
        if (other.getClimateAreaId() != 0) {
          setClimateAreaId(other.getClimateAreaId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                jsonClimateType_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                climateAreaId_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int jsonClimateType_ ;
      /**
       * <code>uint32 json_climate_type = 1;</code>
       * @return The jsonClimateType.
       */
      @Override
      public int getJsonClimateType() {
        return jsonClimateType_;
      }
      /**
       * <code>uint32 json_climate_type = 1;</code>
       * @param value The jsonClimateType to set.
       * @return This builder for chaining.
       */
      public Builder setJsonClimateType(int value) {

        jsonClimateType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 json_climate_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJsonClimateType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonClimateType_ = 0;
        onChanged();
        return this;
      }

      private int climateAreaId_ ;
      /**
       * <code>uint32 climate_area_id = 2;</code>
       * @return The climateAreaId.
       */
      @Override
      public int getClimateAreaId() {
        return climateAreaId_;
      }
      /**
       * <code>uint32 climate_area_id = 2;</code>
       * @param value The climateAreaId to set.
       * @return This builder for chaining.
       */
      public Builder setClimateAreaId(int value) {

        climateAreaId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 climate_area_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClimateAreaId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        climateAreaId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EntityEnvironmentInfo)
    }

    // @@protoc_insertion_point(class_scope:EntityEnvironmentInfo)
    private static final EntityEnvironmentInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EntityEnvironmentInfo();
    }

    public static EntityEnvironmentInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityEnvironmentInfo>
        PARSER = new com.google.protobuf.AbstractParser<EntityEnvironmentInfo>() {
      @Override
      public EntityEnvironmentInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EntityEnvironmentInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EntityEnvironmentInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public EntityEnvironmentInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityEnvironmentInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EntityEnvironmentInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033EntityEnvironmentInfo.proto\"K\n\025EntityE" +
      "nvironmentInfo\022\031\n\021json_climate_type\030\001 \001(" +
      "\r\022\027\n\017climate_area_id\030\002 \001(\rB\032\n\030io.irminsu" +
      "l.common.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EntityEnvironmentInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EntityEnvironmentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EntityEnvironmentInfo_descriptor,
        new String[] { "JsonClimateType", "ClimateAreaId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
