// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: EvtAvatarLockChairReq.proto
// Protobuf Java Version: 4.27.2

package io.irminsul.common.proto;

public final class EvtAvatarLockChairReqOuterClass {
  private EvtAvatarLockChairReqOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      EvtAvatarLockChairReqOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EvtAvatarLockChairReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EvtAvatarLockChairReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Vector position = 13;</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <code>.Vector position = 13;</code>
     * @return The position.
     */
    VectorOuterClass.Vector getPosition();
    /**
     * <code>.Vector position = 13;</code>
     */
    VectorOuterClass.VectorOrBuilder getPositionOrBuilder();

    /**
     * <code>uint64 chair_id = 9;</code>
     * @return The chairId.
     */
    long getChairId();

    /**
     * <code>int32 direction = 3;</code>
     * @return The direction.
     */
    int getDirection();
  }
  /**
   * <pre>
   * CmdId: 23086
   * Obf: LBJMDFGMGBD
   * </pre>
   *
   * Protobuf type {@code EvtAvatarLockChairReq}
   */
  public static final class EvtAvatarLockChairReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EvtAvatarLockChairReq)
      EvtAvatarLockChairReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        EvtAvatarLockChairReq.class.getName());
    }
    // Use EvtAvatarLockChairReq.newBuilder() to construct.
    private EvtAvatarLockChairReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EvtAvatarLockChairReq() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EvtAvatarLockChairReqOuterClass.internal_static_EvtAvatarLockChairReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EvtAvatarLockChairReqOuterClass.internal_static_EvtAvatarLockChairReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EvtAvatarLockChairReq.class, Builder.class);
    }

    private int bitField0_;
    public static final int POSITION_FIELD_NUMBER = 13;
    private VectorOuterClass.Vector position_;
    /**
     * <code>.Vector position = 13;</code>
     * @return Whether the position field is set.
     */
    @Override
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Vector position = 13;</code>
     * @return The position.
     */
    @Override
    public VectorOuterClass.Vector getPosition() {
      return position_ == null ? VectorOuterClass.Vector.getDefaultInstance() : position_;
    }
    /**
     * <code>.Vector position = 13;</code>
     */
    @Override
    public VectorOuterClass.VectorOrBuilder getPositionOrBuilder() {
      return position_ == null ? VectorOuterClass.Vector.getDefaultInstance() : position_;
    }

    public static final int CHAIR_ID_FIELD_NUMBER = 9;
    private long chairId_ = 0L;
    /**
     * <code>uint64 chair_id = 9;</code>
     * @return The chairId.
     */
    @Override
    public long getChairId() {
      return chairId_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 3;
    private int direction_ = 0;
    /**
     * <code>int32 direction = 3;</code>
     * @return The direction.
     */
    @Override
    public int getDirection() {
      return direction_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (direction_ != 0) {
        output.writeInt32(3, direction_);
      }
      if (chairId_ != 0L) {
        output.writeUInt64(9, chairId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(13, getPosition());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (direction_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, direction_);
      }
      if (chairId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, chairId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getPosition());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EvtAvatarLockChairReq)) {
        return super.equals(obj);
      }
      EvtAvatarLockChairReq other = (EvtAvatarLockChairReq) obj;

      if (hasPosition() != other.hasPosition()) return false;
      if (hasPosition()) {
        if (!getPosition()
            .equals(other.getPosition())) return false;
      }
      if (getChairId()
          != other.getChairId()) return false;
      if (getDirection()
          != other.getDirection()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      hash = (37 * hash) + CHAIR_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChairId());
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EvtAvatarLockChairReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EvtAvatarLockChairReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EvtAvatarLockChairReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EvtAvatarLockChairReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EvtAvatarLockChairReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EvtAvatarLockChairReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EvtAvatarLockChairReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EvtAvatarLockChairReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static EvtAvatarLockChairReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static EvtAvatarLockChairReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EvtAvatarLockChairReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EvtAvatarLockChairReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EvtAvatarLockChairReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CmdId: 23086
     * Obf: LBJMDFGMGBD
     * </pre>
     *
     * Protobuf type {@code EvtAvatarLockChairReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EvtAvatarLockChairReq)
        EvtAvatarLockChairReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EvtAvatarLockChairReqOuterClass.internal_static_EvtAvatarLockChairReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EvtAvatarLockChairReqOuterClass.internal_static_EvtAvatarLockChairReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EvtAvatarLockChairReq.class, Builder.class);
      }

      // Construct using io.irminsul.common.proto.EvtAvatarLockChairReqOuterClass.EvtAvatarLockChairReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getPositionFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        position_ = null;
        if (positionBuilder_ != null) {
          positionBuilder_.dispose();
          positionBuilder_ = null;
        }
        chairId_ = 0L;
        direction_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EvtAvatarLockChairReqOuterClass.internal_static_EvtAvatarLockChairReq_descriptor;
      }

      @Override
      public EvtAvatarLockChairReq getDefaultInstanceForType() {
        return EvtAvatarLockChairReq.getDefaultInstance();
      }

      @Override
      public EvtAvatarLockChairReq build() {
        EvtAvatarLockChairReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EvtAvatarLockChairReq buildPartial() {
        EvtAvatarLockChairReq result = new EvtAvatarLockChairReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(EvtAvatarLockChairReq result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.position_ = positionBuilder_ == null
              ? position_
              : positionBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.chairId_ = chairId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.direction_ = direction_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EvtAvatarLockChairReq) {
          return mergeFrom((EvtAvatarLockChairReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EvtAvatarLockChairReq other) {
        if (other == EvtAvatarLockChairReq.getDefaultInstance()) return this;
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.getChairId() != 0L) {
          setChairId(other.getChairId());
        }
        if (other.getDirection() != 0) {
          setDirection(other.getDirection());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 24: {
                direction_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 72: {
                chairId_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 72
              case 106: {
                input.readMessage(
                    getPositionFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 106
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private VectorOuterClass.Vector position_;
      private com.google.protobuf.SingleFieldBuilder<
          VectorOuterClass.Vector, VectorOuterClass.Vector.Builder, VectorOuterClass.VectorOrBuilder> positionBuilder_;
      /**
       * <code>.Vector position = 13;</code>
       * @return Whether the position field is set.
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.Vector position = 13;</code>
       * @return The position.
       */
      public VectorOuterClass.Vector getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? VectorOuterClass.Vector.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>.Vector position = 13;</code>
       */
      public Builder setPosition(VectorOuterClass.Vector value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
        } else {
          positionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Vector position = 13;</code>
       */
      public Builder setPosition(
          VectorOuterClass.Vector.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Vector position = 13;</code>
       */
      public Builder mergePosition(VectorOuterClass.Vector value) {
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            position_ != null &&
            position_ != VectorOuterClass.Vector.getDefaultInstance()) {
            getPositionBuilder().mergeFrom(value);
          } else {
            position_ = value;
          }
        } else {
          positionBuilder_.mergeFrom(value);
        }
        if (position_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Vector position = 13;</code>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000001);
        position_ = null;
        if (positionBuilder_ != null) {
          positionBuilder_.dispose();
          positionBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Vector position = 13;</code>
       */
      public VectorOuterClass.Vector.Builder getPositionBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vector position = 13;</code>
       */
      public VectorOuterClass.VectorOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              VectorOuterClass.Vector.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>.Vector position = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          VectorOuterClass.Vector, VectorOuterClass.Vector.Builder, VectorOuterClass.VectorOrBuilder>
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              VectorOuterClass.Vector, VectorOuterClass.Vector.Builder, VectorOuterClass.VectorOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private long chairId_ ;
      /**
       * <code>uint64 chair_id = 9;</code>
       * @return The chairId.
       */
      @Override
      public long getChairId() {
        return chairId_;
      }
      /**
       * <code>uint64 chair_id = 9;</code>
       * @param value The chairId to set.
       * @return This builder for chaining.
       */
      public Builder setChairId(long value) {

        chairId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 chair_id = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearChairId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chairId_ = 0L;
        onChanged();
        return this;
      }

      private int direction_ ;
      /**
       * <code>int32 direction = 3;</code>
       * @return The direction.
       */
      @Override
      public int getDirection() {
        return direction_;
      }
      /**
       * <code>int32 direction = 3;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(int value) {

        direction_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 direction = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000004);
        direction_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EvtAvatarLockChairReq)
    }

    // @@protoc_insertion_point(class_scope:EvtAvatarLockChairReq)
    private static final EvtAvatarLockChairReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EvtAvatarLockChairReq();
    }

    public static EvtAvatarLockChairReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EvtAvatarLockChairReq>
        PARSER = new com.google.protobuf.AbstractParser<EvtAvatarLockChairReq>() {
      @Override
      public EvtAvatarLockChairReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EvtAvatarLockChairReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EvtAvatarLockChairReq> getParserForType() {
      return PARSER;
    }

    @Override
    public EvtAvatarLockChairReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EvtAvatarLockChairReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EvtAvatarLockChairReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033EvtAvatarLockChairReq.proto\032\014Vector.pr" +
      "oto\"W\n\025EvtAvatarLockChairReq\022\031\n\010position" +
      "\030\r \001(\0132\007.Vector\022\020\n\010chair_id\030\t \001(\004\022\021\n\tdir" +
      "ection\030\003 \001(\005B\032\n\030io.irminsul.common.proto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          VectorOuterClass.getDescriptor(),
        });
    internal_static_EvtAvatarLockChairReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EvtAvatarLockChairReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EvtAvatarLockChairReq_descriptor,
        new String[] { "Position", "ChairId", "Direction", });
    descriptor.resolveAllFeaturesImmutable();
    VectorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
