// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GetAllUnlockNameCardRsp.proto
// Protobuf Java Version: 4.27.2

package io.irminsul.common.proto;

public final class GetAllUnlockNameCardRspOuterClass {
  private GetAllUnlockNameCardRspOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      GetAllUnlockNameCardRspOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetAllUnlockNameCardRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetAllUnlockNameCardRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint32 name_card_list = 8;</code>
     * @return A list containing the nameCardList.
     */
    java.util.List<Integer> getNameCardListList();
    /**
     * <code>repeated uint32 name_card_list = 8;</code>
     * @return The count of nameCardList.
     */
    int getNameCardListCount();
    /**
     * <code>repeated uint32 name_card_list = 8;</code>
     * @param index The index of the element to return.
     * @return The nameCardList at the given index.
     */
    int getNameCardList(int index);

    /**
     * <code>int32 retcode = 9;</code>
     * @return The retcode.
     */
    int getRetcode();
  }
  /**
   * <pre>
   * CmdId: 28550
   * Obf: MIOFHIOGCNF
   * </pre>
   *
   * Protobuf type {@code GetAllUnlockNameCardRsp}
   */
  public static final class GetAllUnlockNameCardRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetAllUnlockNameCardRsp)
      GetAllUnlockNameCardRspOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        GetAllUnlockNameCardRsp.class.getName());
    }
    // Use GetAllUnlockNameCardRsp.newBuilder() to construct.
    private GetAllUnlockNameCardRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetAllUnlockNameCardRsp() {
      nameCardList_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetAllUnlockNameCardRspOuterClass.internal_static_GetAllUnlockNameCardRsp_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetAllUnlockNameCardRspOuterClass.internal_static_GetAllUnlockNameCardRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetAllUnlockNameCardRsp.class, Builder.class);
    }

    public static final int NAME_CARD_LIST_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList nameCardList_ =
        emptyIntList();
    /**
     * <code>repeated uint32 name_card_list = 8;</code>
     * @return A list containing the nameCardList.
     */
    @Override
    public java.util.List<Integer>
        getNameCardListList() {
      return nameCardList_;
    }
    /**
     * <code>repeated uint32 name_card_list = 8;</code>
     * @return The count of nameCardList.
     */
    public int getNameCardListCount() {
      return nameCardList_.size();
    }
    /**
     * <code>repeated uint32 name_card_list = 8;</code>
     * @param index The index of the element to return.
     * @return The nameCardList at the given index.
     */
    public int getNameCardList(int index) {
      return nameCardList_.getInt(index);
    }
    private int nameCardListMemoizedSerializedSize = -1;

    public static final int RETCODE_FIELD_NUMBER = 9;
    private int retcode_ = 0;
    /**
     * <code>int32 retcode = 9;</code>
     * @return The retcode.
     */
    @Override
    public int getRetcode() {
      return retcode_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getNameCardListList().size() > 0) {
        output.writeUInt32NoTag(66);
        output.writeUInt32NoTag(nameCardListMemoizedSerializedSize);
      }
      for (int i = 0; i < nameCardList_.size(); i++) {
        output.writeUInt32NoTag(nameCardList_.getInt(i));
      }
      if (retcode_ != 0) {
        output.writeInt32(9, retcode_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < nameCardList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(nameCardList_.getInt(i));
        }
        size += dataSize;
        if (!getNameCardListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        nameCardListMemoizedSerializedSize = dataSize;
      }
      if (retcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, retcode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetAllUnlockNameCardRsp)) {
        return super.equals(obj);
      }
      GetAllUnlockNameCardRsp other = (GetAllUnlockNameCardRsp) obj;

      if (!getNameCardListList()
          .equals(other.getNameCardListList())) return false;
      if (getRetcode()
          != other.getRetcode()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNameCardListCount() > 0) {
        hash = (37 * hash) + NAME_CARD_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getNameCardListList().hashCode();
      }
      hash = (37 * hash) + RETCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRetcode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetAllUnlockNameCardRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetAllUnlockNameCardRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetAllUnlockNameCardRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetAllUnlockNameCardRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetAllUnlockNameCardRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetAllUnlockNameCardRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetAllUnlockNameCardRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static GetAllUnlockNameCardRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static GetAllUnlockNameCardRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static GetAllUnlockNameCardRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetAllUnlockNameCardRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static GetAllUnlockNameCardRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetAllUnlockNameCardRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CmdId: 28550
     * Obf: MIOFHIOGCNF
     * </pre>
     *
     * Protobuf type {@code GetAllUnlockNameCardRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetAllUnlockNameCardRsp)
        GetAllUnlockNameCardRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetAllUnlockNameCardRspOuterClass.internal_static_GetAllUnlockNameCardRsp_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetAllUnlockNameCardRspOuterClass.internal_static_GetAllUnlockNameCardRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetAllUnlockNameCardRsp.class, Builder.class);
      }

      // Construct using io.irminsul.common.proto.GetAllUnlockNameCardRspOuterClass.GetAllUnlockNameCardRsp.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nameCardList_ = emptyIntList();
        retcode_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetAllUnlockNameCardRspOuterClass.internal_static_GetAllUnlockNameCardRsp_descriptor;
      }

      @Override
      public GetAllUnlockNameCardRsp getDefaultInstanceForType() {
        return GetAllUnlockNameCardRsp.getDefaultInstance();
      }

      @Override
      public GetAllUnlockNameCardRsp build() {
        GetAllUnlockNameCardRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GetAllUnlockNameCardRsp buildPartial() {
        GetAllUnlockNameCardRsp result = new GetAllUnlockNameCardRsp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(GetAllUnlockNameCardRsp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          nameCardList_.makeImmutable();
          result.nameCardList_ = nameCardList_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.retcode_ = retcode_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetAllUnlockNameCardRsp) {
          return mergeFrom((GetAllUnlockNameCardRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetAllUnlockNameCardRsp other) {
        if (other == GetAllUnlockNameCardRsp.getDefaultInstance()) return this;
        if (!other.nameCardList_.isEmpty()) {
          if (nameCardList_.isEmpty()) {
            nameCardList_ = other.nameCardList_;
            nameCardList_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureNameCardListIsMutable();
            nameCardList_.addAll(other.nameCardList_);
          }
          onChanged();
        }
        if (other.getRetcode() != 0) {
          setRetcode(other.getRetcode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 64: {
                int v = input.readUInt32();
                ensureNameCardListIsMutable();
                nameCardList_.addInt(v);
                break;
              } // case 64
              case 66: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureNameCardListIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  nameCardList_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              } // case 66
              case 72: {
                retcode_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList nameCardList_ = emptyIntList();
      private void ensureNameCardListIsMutable() {
        if (!nameCardList_.isModifiable()) {
          nameCardList_ = makeMutableCopy(nameCardList_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated uint32 name_card_list = 8;</code>
       * @return A list containing the nameCardList.
       */
      public java.util.List<Integer>
          getNameCardListList() {
        nameCardList_.makeImmutable();
        return nameCardList_;
      }
      /**
       * <code>repeated uint32 name_card_list = 8;</code>
       * @return The count of nameCardList.
       */
      public int getNameCardListCount() {
        return nameCardList_.size();
      }
      /**
       * <code>repeated uint32 name_card_list = 8;</code>
       * @param index The index of the element to return.
       * @return The nameCardList at the given index.
       */
      public int getNameCardList(int index) {
        return nameCardList_.getInt(index);
      }
      /**
       * <code>repeated uint32 name_card_list = 8;</code>
       * @param index The index to set the value at.
       * @param value The nameCardList to set.
       * @return This builder for chaining.
       */
      public Builder setNameCardList(
          int index, int value) {

        ensureNameCardListIsMutable();
        nameCardList_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 name_card_list = 8;</code>
       * @param value The nameCardList to add.
       * @return This builder for chaining.
       */
      public Builder addNameCardList(int value) {

        ensureNameCardListIsMutable();
        nameCardList_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 name_card_list = 8;</code>
       * @param values The nameCardList to add.
       * @return This builder for chaining.
       */
      public Builder addAllNameCardList(
          Iterable<? extends Integer> values) {
        ensureNameCardListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nameCardList_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 name_card_list = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameCardList() {
        nameCardList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int retcode_ ;
      /**
       * <code>int32 retcode = 9;</code>
       * @return The retcode.
       */
      @Override
      public int getRetcode() {
        return retcode_;
      }
      /**
       * <code>int32 retcode = 9;</code>
       * @param value The retcode to set.
       * @return This builder for chaining.
       */
      public Builder setRetcode(int value) {

        retcode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retcode = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetcode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retcode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetAllUnlockNameCardRsp)
    }

    // @@protoc_insertion_point(class_scope:GetAllUnlockNameCardRsp)
    private static final GetAllUnlockNameCardRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetAllUnlockNameCardRsp();
    }

    public static GetAllUnlockNameCardRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAllUnlockNameCardRsp>
        PARSER = new com.google.protobuf.AbstractParser<GetAllUnlockNameCardRsp>() {
      @Override
      public GetAllUnlockNameCardRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetAllUnlockNameCardRsp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetAllUnlockNameCardRsp> getParserForType() {
      return PARSER;
    }

    @Override
    public GetAllUnlockNameCardRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllUnlockNameCardRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetAllUnlockNameCardRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035GetAllUnlockNameCardRsp.proto\"B\n\027GetAl" +
      "lUnlockNameCardRsp\022\026\n\016name_card_list\030\010 \003" +
      "(\r\022\017\n\007retcode\030\t \001(\005B\032\n\030io.irminsul.commo" +
      "n.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetAllUnlockNameCardRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetAllUnlockNameCardRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetAllUnlockNameCardRsp_descriptor,
        new String[] { "NameCardList", "Retcode", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
