package io.irminsul.common.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryCurrRegionHttpRsp.proto

// Protobuf Java Version: 3.25.4
public final class QueryCurrRegionHttpRspOuterClass {
  private QueryCurrRegionHttpRspOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryCurrRegionHttpRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueryCurrRegionHttpRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 retcode = 1;</code>
     * @return The retcode.
     */
    int getRetcode();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>.RegionInfo region_info = 3;</code>
     * @return Whether the regionInfo field is set.
     */
    boolean hasRegionInfo();
    /**
     * <code>.RegionInfo region_info = 3;</code>
     * @return The regionInfo.
     */
    RegionInfoOuterClass.RegionInfo getRegionInfo();
    /**
     * <code>.RegionInfo region_info = 3;</code>
     */
    RegionInfoOuterClass.RegionInfoOrBuilder getRegionInfoOrBuilder();

    /**
     * <code>bytes client_secret_key = 11;</code>
     * @return The clientSecretKey.
     */
    com.google.protobuf.ByteString getClientSecretKey();

    /**
     * <code>bytes region_custom_config_encrypted = 12;</code>
     * @return The regionCustomConfigEncrypted.
     */
    com.google.protobuf.ByteString getRegionCustomConfigEncrypted();

    /**
     * <code>bytes client_region_custom_config_encrypted = 13;</code>
     * @return The clientRegionCustomConfigEncrypted.
     */
    com.google.protobuf.ByteString getClientRegionCustomConfigEncrypted();

    /**
     * <code>.ForceUpdateInfo force_udpate = 4;</code>
     * @return Whether the forceUdpate field is set.
     */
    boolean hasForceUdpate();
    /**
     * <code>.ForceUpdateInfo force_udpate = 4;</code>
     * @return The forceUdpate.
     */
    ForceUpdateInfoOuterClass.ForceUpdateInfo getForceUdpate();
    /**
     * <code>.ForceUpdateInfo force_udpate = 4;</code>
     */
    ForceUpdateInfoOuterClass.ForceUpdateInfoOrBuilder getForceUdpateOrBuilder();

    /**
     * <code>.StopServerInfo stop_server = 5;</code>
     * @return Whether the stopServer field is set.
     */
    boolean hasStopServer();
    /**
     * <code>.StopServerInfo stop_server = 5;</code>
     * @return The stopServer.
     */
    StopServerInfoOuterClass.StopServerInfo getStopServer();
    /**
     * <code>.StopServerInfo stop_server = 5;</code>
     */
    StopServerInfoOuterClass.StopServerInfoOrBuilder getStopServerOrBuilder();

    QueryCurrRegionHttpRsp.DetailCase getDetailCase();
  }
  /**
   * Protobuf type {@code QueryCurrRegionHttpRsp}
   */
  public static final class QueryCurrRegionHttpRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QueryCurrRegionHttpRsp)
      QueryCurrRegionHttpRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryCurrRegionHttpRsp.newBuilder() to construct.
    private QueryCurrRegionHttpRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryCurrRegionHttpRsp() {
      msg_ = "";
      clientSecretKey_ = com.google.protobuf.ByteString.EMPTY;
      regionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      clientRegionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryCurrRegionHttpRsp();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryCurrRegionHttpRsp.class, Builder.class);
    }

    private int bitField0_;
    private int detailCase_ = 0;
    @SuppressWarnings("serial")
    private Object detail_;
    public enum DetailCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      FORCE_UDPATE(4),
      STOP_SERVER(5),
      DETAIL_NOT_SET(0);
      private final int value;
      private DetailCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DetailCase valueOf(int value) {
        return forNumber(value);
      }

      public static DetailCase forNumber(int value) {
        switch (value) {
          case 4: return FORCE_UDPATE;
          case 5: return STOP_SERVER;
          case 0: return DETAIL_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DetailCase
    getDetailCase() {
      return DetailCase.forNumber(
          detailCase_);
    }

    public static final int RETCODE_FIELD_NUMBER = 1;
    private int retcode_ = 0;
    /**
     * <code>int32 retcode = 1;</code>
     * @return The retcode.
     */
    @Override
    public int getRetcode() {
      return retcode_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object msg_ = "";
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @Override
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_INFO_FIELD_NUMBER = 3;
    private RegionInfoOuterClass.RegionInfo regionInfo_;
    /**
     * <code>.RegionInfo region_info = 3;</code>
     * @return Whether the regionInfo field is set.
     */
    @Override
    public boolean hasRegionInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.RegionInfo region_info = 3;</code>
     * @return The regionInfo.
     */
    @Override
    public RegionInfoOuterClass.RegionInfo getRegionInfo() {
      return regionInfo_ == null ? RegionInfoOuterClass.RegionInfo.getDefaultInstance() : regionInfo_;
    }
    /**
     * <code>.RegionInfo region_info = 3;</code>
     */
    @Override
    public RegionInfoOuterClass.RegionInfoOrBuilder getRegionInfoOrBuilder() {
      return regionInfo_ == null ? RegionInfoOuterClass.RegionInfo.getDefaultInstance() : regionInfo_;
    }

    public static final int CLIENT_SECRET_KEY_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString clientSecretKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes client_secret_key = 11;</code>
     * @return The clientSecretKey.
     */
    @Override
    public com.google.protobuf.ByteString getClientSecretKey() {
      return clientSecretKey_;
    }

    public static final int REGION_CUSTOM_CONFIG_ENCRYPTED_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString regionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes region_custom_config_encrypted = 12;</code>
     * @return The regionCustomConfigEncrypted.
     */
    @Override
    public com.google.protobuf.ByteString getRegionCustomConfigEncrypted() {
      return regionCustomConfigEncrypted_;
    }

    public static final int CLIENT_REGION_CUSTOM_CONFIG_ENCRYPTED_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString clientRegionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes client_region_custom_config_encrypted = 13;</code>
     * @return The clientRegionCustomConfigEncrypted.
     */
    @Override
    public com.google.protobuf.ByteString getClientRegionCustomConfigEncrypted() {
      return clientRegionCustomConfigEncrypted_;
    }

    public static final int FORCE_UDPATE_FIELD_NUMBER = 4;
    /**
     * <code>.ForceUpdateInfo force_udpate = 4;</code>
     * @return Whether the forceUdpate field is set.
     */
    @Override
    public boolean hasForceUdpate() {
      return detailCase_ == 4;
    }
    /**
     * <code>.ForceUpdateInfo force_udpate = 4;</code>
     * @return The forceUdpate.
     */
    @Override
    public ForceUpdateInfoOuterClass.ForceUpdateInfo getForceUdpate() {
      if (detailCase_ == 4) {
         return (ForceUpdateInfoOuterClass.ForceUpdateInfo) detail_;
      }
      return ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance();
    }
    /**
     * <code>.ForceUpdateInfo force_udpate = 4;</code>
     */
    @Override
    public ForceUpdateInfoOuterClass.ForceUpdateInfoOrBuilder getForceUdpateOrBuilder() {
      if (detailCase_ == 4) {
         return (ForceUpdateInfoOuterClass.ForceUpdateInfo) detail_;
      }
      return ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance();
    }

    public static final int STOP_SERVER_FIELD_NUMBER = 5;
    /**
     * <code>.StopServerInfo stop_server = 5;</code>
     * @return Whether the stopServer field is set.
     */
    @Override
    public boolean hasStopServer() {
      return detailCase_ == 5;
    }
    /**
     * <code>.StopServerInfo stop_server = 5;</code>
     * @return The stopServer.
     */
    @Override
    public StopServerInfoOuterClass.StopServerInfo getStopServer() {
      if (detailCase_ == 5) {
         return (StopServerInfoOuterClass.StopServerInfo) detail_;
      }
      return StopServerInfoOuterClass.StopServerInfo.getDefaultInstance();
    }
    /**
     * <code>.StopServerInfo stop_server = 5;</code>
     */
    @Override
    public StopServerInfoOuterClass.StopServerInfoOrBuilder getStopServerOrBuilder() {
      if (detailCase_ == 5) {
         return (StopServerInfoOuterClass.StopServerInfo) detail_;
      }
      return StopServerInfoOuterClass.StopServerInfo.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (retcode_ != 0) {
        output.writeInt32(1, retcode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getRegionInfo());
      }
      if (detailCase_ == 4) {
        output.writeMessage(4, (ForceUpdateInfoOuterClass.ForceUpdateInfo) detail_);
      }
      if (detailCase_ == 5) {
        output.writeMessage(5, (StopServerInfoOuterClass.StopServerInfo) detail_);
      }
      if (!clientSecretKey_.isEmpty()) {
        output.writeBytes(11, clientSecretKey_);
      }
      if (!regionCustomConfigEncrypted_.isEmpty()) {
        output.writeBytes(12, regionCustomConfigEncrypted_);
      }
      if (!clientRegionCustomConfigEncrypted_.isEmpty()) {
        output.writeBytes(13, clientRegionCustomConfigEncrypted_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (retcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retcode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRegionInfo());
      }
      if (detailCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (ForceUpdateInfoOuterClass.ForceUpdateInfo) detail_);
      }
      if (detailCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (StopServerInfoOuterClass.StopServerInfo) detail_);
      }
      if (!clientSecretKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, clientSecretKey_);
      }
      if (!regionCustomConfigEncrypted_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, regionCustomConfigEncrypted_);
      }
      if (!clientRegionCustomConfigEncrypted_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, clientRegionCustomConfigEncrypted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QueryCurrRegionHttpRsp)) {
        return super.equals(obj);
      }
      QueryCurrRegionHttpRsp other = (QueryCurrRegionHttpRsp) obj;

      if (getRetcode()
          != other.getRetcode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (hasRegionInfo() != other.hasRegionInfo()) return false;
      if (hasRegionInfo()) {
        if (!getRegionInfo()
            .equals(other.getRegionInfo())) return false;
      }
      if (!getClientSecretKey()
          .equals(other.getClientSecretKey())) return false;
      if (!getRegionCustomConfigEncrypted()
          .equals(other.getRegionCustomConfigEncrypted())) return false;
      if (!getClientRegionCustomConfigEncrypted()
          .equals(other.getClientRegionCustomConfigEncrypted())) return false;
      if (!getDetailCase().equals(other.getDetailCase())) return false;
      switch (detailCase_) {
        case 4:
          if (!getForceUdpate()
              .equals(other.getForceUdpate())) return false;
          break;
        case 5:
          if (!getStopServer()
              .equals(other.getStopServer())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RETCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRetcode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (hasRegionInfo()) {
        hash = (37 * hash) + REGION_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getRegionInfo().hashCode();
      }
      hash = (37 * hash) + CLIENT_SECRET_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getClientSecretKey().hashCode();
      hash = (37 * hash) + REGION_CUSTOM_CONFIG_ENCRYPTED_FIELD_NUMBER;
      hash = (53 * hash) + getRegionCustomConfigEncrypted().hashCode();
      hash = (37 * hash) + CLIENT_REGION_CUSTOM_CONFIG_ENCRYPTED_FIELD_NUMBER;
      hash = (53 * hash) + getClientRegionCustomConfigEncrypted().hashCode();
      switch (detailCase_) {
        case 4:
          hash = (37 * hash) + FORCE_UDPATE_FIELD_NUMBER;
          hash = (53 * hash) + getForceUdpate().hashCode();
          break;
        case 5:
          hash = (37 * hash) + STOP_SERVER_FIELD_NUMBER;
          hash = (53 * hash) + getStopServer().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QueryCurrRegionHttpRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryCurrRegionHttpRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryCurrRegionHttpRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryCurrRegionHttpRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryCurrRegionHttpRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryCurrRegionHttpRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryCurrRegionHttpRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QueryCurrRegionHttpRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static QueryCurrRegionHttpRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static QueryCurrRegionHttpRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QueryCurrRegionHttpRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QueryCurrRegionHttpRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QueryCurrRegionHttpRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryCurrRegionHttpRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueryCurrRegionHttpRsp)
        QueryCurrRegionHttpRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueryCurrRegionHttpRsp.class, Builder.class);
      }

      // Construct using QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRegionInfoFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        retcode_ = 0;
        msg_ = "";
        regionInfo_ = null;
        if (regionInfoBuilder_ != null) {
          regionInfoBuilder_.dispose();
          regionInfoBuilder_ = null;
        }
        clientSecretKey_ = com.google.protobuf.ByteString.EMPTY;
        regionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
        clientRegionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
        if (forceUdpateBuilder_ != null) {
          forceUdpateBuilder_.clear();
        }
        if (stopServerBuilder_ != null) {
          stopServerBuilder_.clear();
        }
        detailCase_ = 0;
        detail_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_descriptor;
      }

      @Override
      public QueryCurrRegionHttpRsp getDefaultInstanceForType() {
        return QueryCurrRegionHttpRsp.getDefaultInstance();
      }

      @Override
      public QueryCurrRegionHttpRsp build() {
        QueryCurrRegionHttpRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public QueryCurrRegionHttpRsp buildPartial() {
        QueryCurrRegionHttpRsp result = new QueryCurrRegionHttpRsp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(QueryCurrRegionHttpRsp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.retcode_ = retcode_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msg_ = msg_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.regionInfo_ = regionInfoBuilder_ == null
              ? regionInfo_
              : regionInfoBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.clientSecretKey_ = clientSecretKey_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.regionCustomConfigEncrypted_ = regionCustomConfigEncrypted_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.clientRegionCustomConfigEncrypted_ = clientRegionCustomConfigEncrypted_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      private void buildPartialOneofs(QueryCurrRegionHttpRsp result) {
        result.detailCase_ = detailCase_;
        result.detail_ = this.detail_;
        if (detailCase_ == 4 &&
            forceUdpateBuilder_ != null) {
          result.detail_ = forceUdpateBuilder_.build();
        }
        if (detailCase_ == 5 &&
            stopServerBuilder_ != null) {
          result.detail_ = stopServerBuilder_.build();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryCurrRegionHttpRsp) {
          return mergeFrom((QueryCurrRegionHttpRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueryCurrRegionHttpRsp other) {
        if (other == QueryCurrRegionHttpRsp.getDefaultInstance()) return this;
        if (other.getRetcode() != 0) {
          setRetcode(other.getRetcode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasRegionInfo()) {
          mergeRegionInfo(other.getRegionInfo());
        }
        if (other.getClientSecretKey() != com.google.protobuf.ByteString.EMPTY) {
          setClientSecretKey(other.getClientSecretKey());
        }
        if (other.getRegionCustomConfigEncrypted() != com.google.protobuf.ByteString.EMPTY) {
          setRegionCustomConfigEncrypted(other.getRegionCustomConfigEncrypted());
        }
        if (other.getClientRegionCustomConfigEncrypted() != com.google.protobuf.ByteString.EMPTY) {
          setClientRegionCustomConfigEncrypted(other.getClientRegionCustomConfigEncrypted());
        }
        switch (other.getDetailCase()) {
          case FORCE_UDPATE: {
            mergeForceUdpate(other.getForceUdpate());
            break;
          }
          case STOP_SERVER: {
            mergeStopServer(other.getStopServer());
            break;
          }
          case DETAIL_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                retcode_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                msg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getRegionInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getForceUdpateFieldBuilder().getBuilder(),
                    extensionRegistry);
                detailCase_ = 4;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getStopServerFieldBuilder().getBuilder(),
                    extensionRegistry);
                detailCase_ = 5;
                break;
              } // case 42
              case 90: {
                clientSecretKey_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 90
              case 98: {
                regionCustomConfigEncrypted_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 98
              case 106: {
                clientRegionCustomConfigEncrypted_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 106
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int detailCase_ = 0;
      private Object detail_;
      public DetailCase
          getDetailCase() {
        return DetailCase.forNumber(
            detailCase_);
      }

      public Builder clearDetail() {
        detailCase_ = 0;
        detail_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int retcode_ ;
      /**
       * <code>int32 retcode = 1;</code>
       * @return The retcode.
       */
      @Override
      public int getRetcode() {
        return retcode_;
      }
      /**
       * <code>int32 retcode = 1;</code>
       * @param value The retcode to set.
       * @return This builder for chaining.
       */
      public Builder setRetcode(int value) {

        retcode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retcode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retcode_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        msg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        msg_ = getDefaultInstance().getMsg();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        msg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private RegionInfoOuterClass.RegionInfo regionInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          RegionInfoOuterClass.RegionInfo, RegionInfoOuterClass.RegionInfo.Builder, RegionInfoOuterClass.RegionInfoOrBuilder> regionInfoBuilder_;
      /**
       * <code>.RegionInfo region_info = 3;</code>
       * @return Whether the regionInfo field is set.
       */
      public boolean hasRegionInfo() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       * @return The regionInfo.
       */
      public RegionInfoOuterClass.RegionInfo getRegionInfo() {
        if (regionInfoBuilder_ == null) {
          return regionInfo_ == null ? RegionInfoOuterClass.RegionInfo.getDefaultInstance() : regionInfo_;
        } else {
          return regionInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public Builder setRegionInfo(RegionInfoOuterClass.RegionInfo value) {
        if (regionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          regionInfo_ = value;
        } else {
          regionInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public Builder setRegionInfo(
          RegionInfoOuterClass.RegionInfo.Builder builderForValue) {
        if (regionInfoBuilder_ == null) {
          regionInfo_ = builderForValue.build();
        } else {
          regionInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public Builder mergeRegionInfo(RegionInfoOuterClass.RegionInfo value) {
        if (regionInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            regionInfo_ != null &&
            regionInfo_ != RegionInfoOuterClass.RegionInfo.getDefaultInstance()) {
            getRegionInfoBuilder().mergeFrom(value);
          } else {
            regionInfo_ = value;
          }
        } else {
          regionInfoBuilder_.mergeFrom(value);
        }
        if (regionInfo_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public Builder clearRegionInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        regionInfo_ = null;
        if (regionInfoBuilder_ != null) {
          regionInfoBuilder_.dispose();
          regionInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public RegionInfoOuterClass.RegionInfo.Builder getRegionInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRegionInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public RegionInfoOuterClass.RegionInfoOrBuilder getRegionInfoOrBuilder() {
        if (regionInfoBuilder_ != null) {
          return regionInfoBuilder_.getMessageOrBuilder();
        } else {
          return regionInfo_ == null ?
              RegionInfoOuterClass.RegionInfo.getDefaultInstance() : regionInfo_;
        }
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RegionInfoOuterClass.RegionInfo, RegionInfoOuterClass.RegionInfo.Builder, RegionInfoOuterClass.RegionInfoOrBuilder> 
          getRegionInfoFieldBuilder() {
        if (regionInfoBuilder_ == null) {
          regionInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RegionInfoOuterClass.RegionInfo, RegionInfoOuterClass.RegionInfo.Builder, RegionInfoOuterClass.RegionInfoOrBuilder>(
                  getRegionInfo(),
                  getParentForChildren(),
                  isClean());
          regionInfo_ = null;
        }
        return regionInfoBuilder_;
      }

      private com.google.protobuf.ByteString clientSecretKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes client_secret_key = 11;</code>
       * @return The clientSecretKey.
       */
      @Override
      public com.google.protobuf.ByteString getClientSecretKey() {
        return clientSecretKey_;
      }
      /**
       * <code>bytes client_secret_key = 11;</code>
       * @param value The clientSecretKey to set.
       * @return This builder for chaining.
       */
      public Builder setClientSecretKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        clientSecretKey_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bytes client_secret_key = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientSecretKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientSecretKey_ = getDefaultInstance().getClientSecretKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString regionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes region_custom_config_encrypted = 12;</code>
       * @return The regionCustomConfigEncrypted.
       */
      @Override
      public com.google.protobuf.ByteString getRegionCustomConfigEncrypted() {
        return regionCustomConfigEncrypted_;
      }
      /**
       * <code>bytes region_custom_config_encrypted = 12;</code>
       * @param value The regionCustomConfigEncrypted to set.
       * @return This builder for chaining.
       */
      public Builder setRegionCustomConfigEncrypted(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        regionCustomConfigEncrypted_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bytes region_custom_config_encrypted = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegionCustomConfigEncrypted() {
        bitField0_ = (bitField0_ & ~0x00000010);
        regionCustomConfigEncrypted_ = getDefaultInstance().getRegionCustomConfigEncrypted();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString clientRegionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes client_region_custom_config_encrypted = 13;</code>
       * @return The clientRegionCustomConfigEncrypted.
       */
      @Override
      public com.google.protobuf.ByteString getClientRegionCustomConfigEncrypted() {
        return clientRegionCustomConfigEncrypted_;
      }
      /**
       * <code>bytes client_region_custom_config_encrypted = 13;</code>
       * @param value The clientRegionCustomConfigEncrypted to set.
       * @return This builder for chaining.
       */
      public Builder setClientRegionCustomConfigEncrypted(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        clientRegionCustomConfigEncrypted_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bytes client_region_custom_config_encrypted = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientRegionCustomConfigEncrypted() {
        bitField0_ = (bitField0_ & ~0x00000020);
        clientRegionCustomConfigEncrypted_ = getDefaultInstance().getClientRegionCustomConfigEncrypted();
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ForceUpdateInfoOuterClass.ForceUpdateInfo, ForceUpdateInfoOuterClass.ForceUpdateInfo.Builder, ForceUpdateInfoOuterClass.ForceUpdateInfoOrBuilder> forceUdpateBuilder_;
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       * @return Whether the forceUdpate field is set.
       */
      @Override
      public boolean hasForceUdpate() {
        return detailCase_ == 4;
      }
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       * @return The forceUdpate.
       */
      @Override
      public ForceUpdateInfoOuterClass.ForceUpdateInfo getForceUdpate() {
        if (forceUdpateBuilder_ == null) {
          if (detailCase_ == 4) {
            return (ForceUpdateInfoOuterClass.ForceUpdateInfo) detail_;
          }
          return ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance();
        } else {
          if (detailCase_ == 4) {
            return forceUdpateBuilder_.getMessage();
          }
          return ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       */
      public Builder setForceUdpate(ForceUpdateInfoOuterClass.ForceUpdateInfo value) {
        if (forceUdpateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          detail_ = value;
          onChanged();
        } else {
          forceUdpateBuilder_.setMessage(value);
        }
        detailCase_ = 4;
        return this;
      }
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       */
      public Builder setForceUdpate(
          ForceUpdateInfoOuterClass.ForceUpdateInfo.Builder builderForValue) {
        if (forceUdpateBuilder_ == null) {
          detail_ = builderForValue.build();
          onChanged();
        } else {
          forceUdpateBuilder_.setMessage(builderForValue.build());
        }
        detailCase_ = 4;
        return this;
      }
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       */
      public Builder mergeForceUdpate(ForceUpdateInfoOuterClass.ForceUpdateInfo value) {
        if (forceUdpateBuilder_ == null) {
          if (detailCase_ == 4 &&
              detail_ != ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance()) {
            detail_ = ForceUpdateInfoOuterClass.ForceUpdateInfo.newBuilder((ForceUpdateInfoOuterClass.ForceUpdateInfo) detail_)
                .mergeFrom(value).buildPartial();
          } else {
            detail_ = value;
          }
          onChanged();
        } else {
          if (detailCase_ == 4) {
            forceUdpateBuilder_.mergeFrom(value);
          } else {
            forceUdpateBuilder_.setMessage(value);
          }
        }
        detailCase_ = 4;
        return this;
      }
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       */
      public Builder clearForceUdpate() {
        if (forceUdpateBuilder_ == null) {
          if (detailCase_ == 4) {
            detailCase_ = 0;
            detail_ = null;
            onChanged();
          }
        } else {
          if (detailCase_ == 4) {
            detailCase_ = 0;
            detail_ = null;
          }
          forceUdpateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       */
      public ForceUpdateInfoOuterClass.ForceUpdateInfo.Builder getForceUdpateBuilder() {
        return getForceUdpateFieldBuilder().getBuilder();
      }
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       */
      @Override
      public ForceUpdateInfoOuterClass.ForceUpdateInfoOrBuilder getForceUdpateOrBuilder() {
        if ((detailCase_ == 4) && (forceUdpateBuilder_ != null)) {
          return forceUdpateBuilder_.getMessageOrBuilder();
        } else {
          if (detailCase_ == 4) {
            return (ForceUpdateInfoOuterClass.ForceUpdateInfo) detail_;
          }
          return ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.ForceUpdateInfo force_udpate = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ForceUpdateInfoOuterClass.ForceUpdateInfo, ForceUpdateInfoOuterClass.ForceUpdateInfo.Builder, ForceUpdateInfoOuterClass.ForceUpdateInfoOrBuilder> 
          getForceUdpateFieldBuilder() {
        if (forceUdpateBuilder_ == null) {
          if (!(detailCase_ == 4)) {
            detail_ = ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance();
          }
          forceUdpateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ForceUpdateInfoOuterClass.ForceUpdateInfo, ForceUpdateInfoOuterClass.ForceUpdateInfo.Builder, ForceUpdateInfoOuterClass.ForceUpdateInfoOrBuilder>(
                  (ForceUpdateInfoOuterClass.ForceUpdateInfo) detail_,
                  getParentForChildren(),
                  isClean());
          detail_ = null;
        }
        detailCase_ = 4;
        onChanged();
        return forceUdpateBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          StopServerInfoOuterClass.StopServerInfo, StopServerInfoOuterClass.StopServerInfo.Builder, StopServerInfoOuterClass.StopServerInfoOrBuilder> stopServerBuilder_;
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       * @return Whether the stopServer field is set.
       */
      @Override
      public boolean hasStopServer() {
        return detailCase_ == 5;
      }
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       * @return The stopServer.
       */
      @Override
      public StopServerInfoOuterClass.StopServerInfo getStopServer() {
        if (stopServerBuilder_ == null) {
          if (detailCase_ == 5) {
            return (StopServerInfoOuterClass.StopServerInfo) detail_;
          }
          return StopServerInfoOuterClass.StopServerInfo.getDefaultInstance();
        } else {
          if (detailCase_ == 5) {
            return stopServerBuilder_.getMessage();
          }
          return StopServerInfoOuterClass.StopServerInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       */
      public Builder setStopServer(StopServerInfoOuterClass.StopServerInfo value) {
        if (stopServerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          detail_ = value;
          onChanged();
        } else {
          stopServerBuilder_.setMessage(value);
        }
        detailCase_ = 5;
        return this;
      }
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       */
      public Builder setStopServer(
          StopServerInfoOuterClass.StopServerInfo.Builder builderForValue) {
        if (stopServerBuilder_ == null) {
          detail_ = builderForValue.build();
          onChanged();
        } else {
          stopServerBuilder_.setMessage(builderForValue.build());
        }
        detailCase_ = 5;
        return this;
      }
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       */
      public Builder mergeStopServer(StopServerInfoOuterClass.StopServerInfo value) {
        if (stopServerBuilder_ == null) {
          if (detailCase_ == 5 &&
              detail_ != StopServerInfoOuterClass.StopServerInfo.getDefaultInstance()) {
            detail_ = StopServerInfoOuterClass.StopServerInfo.newBuilder((StopServerInfoOuterClass.StopServerInfo) detail_)
                .mergeFrom(value).buildPartial();
          } else {
            detail_ = value;
          }
          onChanged();
        } else {
          if (detailCase_ == 5) {
            stopServerBuilder_.mergeFrom(value);
          } else {
            stopServerBuilder_.setMessage(value);
          }
        }
        detailCase_ = 5;
        return this;
      }
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       */
      public Builder clearStopServer() {
        if (stopServerBuilder_ == null) {
          if (detailCase_ == 5) {
            detailCase_ = 0;
            detail_ = null;
            onChanged();
          }
        } else {
          if (detailCase_ == 5) {
            detailCase_ = 0;
            detail_ = null;
          }
          stopServerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       */
      public StopServerInfoOuterClass.StopServerInfo.Builder getStopServerBuilder() {
        return getStopServerFieldBuilder().getBuilder();
      }
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       */
      @Override
      public StopServerInfoOuterClass.StopServerInfoOrBuilder getStopServerOrBuilder() {
        if ((detailCase_ == 5) && (stopServerBuilder_ != null)) {
          return stopServerBuilder_.getMessageOrBuilder();
        } else {
          if (detailCase_ == 5) {
            return (StopServerInfoOuterClass.StopServerInfo) detail_;
          }
          return StopServerInfoOuterClass.StopServerInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.StopServerInfo stop_server = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          StopServerInfoOuterClass.StopServerInfo, StopServerInfoOuterClass.StopServerInfo.Builder, StopServerInfoOuterClass.StopServerInfoOrBuilder> 
          getStopServerFieldBuilder() {
        if (stopServerBuilder_ == null) {
          if (!(detailCase_ == 5)) {
            detail_ = StopServerInfoOuterClass.StopServerInfo.getDefaultInstance();
          }
          stopServerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              StopServerInfoOuterClass.StopServerInfo, StopServerInfoOuterClass.StopServerInfo.Builder, StopServerInfoOuterClass.StopServerInfoOrBuilder>(
                  (StopServerInfoOuterClass.StopServerInfo) detail_,
                  getParentForChildren(),
                  isClean());
          detail_ = null;
        }
        detailCase_ = 5;
        onChanged();
        return stopServerBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QueryCurrRegionHttpRsp)
    }

    // @@protoc_insertion_point(class_scope:QueryCurrRegionHttpRsp)
    private static final QueryCurrRegionHttpRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QueryCurrRegionHttpRsp();
    }

    public static QueryCurrRegionHttpRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryCurrRegionHttpRsp>
        PARSER = new com.google.protobuf.AbstractParser<QueryCurrRegionHttpRsp>() {
      @Override
      public QueryCurrRegionHttpRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QueryCurrRegionHttpRsp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<QueryCurrRegionHttpRsp> getParserForType() {
      return PARSER;
    }

    @Override
    public QueryCurrRegionHttpRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryCurrRegionHttpRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryCurrRegionHttpRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034QueryCurrRegionHttpRsp.proto\032\020RegionIn" +
      "fo.proto\032\025ForceUpdateInfo.proto\032\024StopSer" +
      "verInfo.proto\"\246\002\n\026QueryCurrRegionHttpRsp" +
      "\022\017\n\007retcode\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022 \n\013region" +
      "_info\030\003 \001(\0132\013.RegionInfo\022\031\n\021client_secre" +
      "t_key\030\013 \001(\014\022&\n\036region_custom_config_encr" +
      "ypted\030\014 \001(\014\022-\n%client_region_custom_conf" +
      "ig_encrypted\030\r \001(\014\022(\n\014force_udpate\030\004 \001(\013" +
      "2\020.ForceUpdateInfoH\000\022&\n\013stop_server\030\005 \001(" +
      "\0132\017.StopServerInfoH\000B\010\n\006detailb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          RegionInfoOuterClass.getDescriptor(),
          ForceUpdateInfoOuterClass.getDescriptor(),
          StopServerInfoOuterClass.getDescriptor(),
        });
    internal_static_QueryCurrRegionHttpRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryCurrRegionHttpRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryCurrRegionHttpRsp_descriptor,
        new String[] { "Retcode", "Msg", "RegionInfo", "ClientSecretKey", "RegionCustomConfigEncrypted", "ClientRegionCustomConfigEncrypted", "ForceUdpate", "StopServer", "Detail", });
    RegionInfoOuterClass.getDescriptor();
    ForceUpdateInfoOuterClass.getDescriptor();
    StopServerInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
