// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Route.proto
// Protobuf Java Version: 4.27.2

package io.irminsul.common.proto;

public final class RouteOuterClass {
  private RouteOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      RouteOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RouteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Route)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    java.util.List<RoutePointOuterClass.RoutePoint>
        getRoutePointsList();
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    RoutePointOuterClass.RoutePoint getRoutePoints(int index);
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    int getRoutePointsCount();
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    java.util.List<? extends RoutePointOuterClass.RoutePointOrBuilder>
        getRoutePointsOrBuilderList();
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    RoutePointOuterClass.RoutePointOrBuilder getRoutePointsOrBuilder(
        int index);

    /**
     * <code>uint32 route_type = 2;</code>
     * @return The routeType.
     */
    int getRouteType();
  }
  /**
   * <pre>
   * Obf: GPFODIPKJPN
   * </pre>
   *
   * Protobuf type {@code Route}
   */
  public static final class Route extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Route)
      RouteOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        Route.class.getName());
    }
    // Use Route.newBuilder() to construct.
    private Route(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Route() {
      routePoints_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouteOuterClass.internal_static_Route_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouteOuterClass.internal_static_Route_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Route.class, Builder.class);
    }

    public static final int ROUTE_POINTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<RoutePointOuterClass.RoutePoint> routePoints_;
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    @Override
    public java.util.List<RoutePointOuterClass.RoutePoint> getRoutePointsList() {
      return routePoints_;
    }
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    @Override
    public java.util.List<? extends RoutePointOuterClass.RoutePointOrBuilder>
        getRoutePointsOrBuilderList() {
      return routePoints_;
    }
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    @Override
    public int getRoutePointsCount() {
      return routePoints_.size();
    }
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    @Override
    public RoutePointOuterClass.RoutePoint getRoutePoints(int index) {
      return routePoints_.get(index);
    }
    /**
     * <code>repeated .RoutePoint route_points = 1;</code>
     */
    @Override
    public RoutePointOuterClass.RoutePointOrBuilder getRoutePointsOrBuilder(
        int index) {
      return routePoints_.get(index);
    }

    public static final int ROUTE_TYPE_FIELD_NUMBER = 2;
    private int routeType_ = 0;
    /**
     * <code>uint32 route_type = 2;</code>
     * @return The routeType.
     */
    @Override
    public int getRouteType() {
      return routeType_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < routePoints_.size(); i++) {
        output.writeMessage(1, routePoints_.get(i));
      }
      if (routeType_ != 0) {
        output.writeUInt32(2, routeType_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < routePoints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, routePoints_.get(i));
      }
      if (routeType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, routeType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Route)) {
        return super.equals(obj);
      }
      Route other = (Route) obj;

      if (!getRoutePointsList()
          .equals(other.getRoutePointsList())) return false;
      if (getRouteType()
          != other.getRouteType()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRoutePointsCount() > 0) {
        hash = (37 * hash) + ROUTE_POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getRoutePointsList().hashCode();
      }
      hash = (37 * hash) + ROUTE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRouteType();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Route parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Route parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Route parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Route parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Route parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Route parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Route parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Route parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Route parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Route parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Route parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Route parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Route prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Obf: GPFODIPKJPN
     * </pre>
     *
     * Protobuf type {@code Route}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Route)
        RouteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RouteOuterClass.internal_static_Route_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RouteOuterClass.internal_static_Route_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Route.class, Builder.class);
      }

      // Construct using io.irminsul.common.proto.RouteOuterClass.Route.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (routePointsBuilder_ == null) {
          routePoints_ = java.util.Collections.emptyList();
        } else {
          routePoints_ = null;
          routePointsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        routeType_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RouteOuterClass.internal_static_Route_descriptor;
      }

      @Override
      public Route getDefaultInstanceForType() {
        return Route.getDefaultInstance();
      }

      @Override
      public Route build() {
        Route result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Route buildPartial() {
        Route result = new Route(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Route result) {
        if (routePointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            routePoints_ = java.util.Collections.unmodifiableList(routePoints_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.routePoints_ = routePoints_;
        } else {
          result.routePoints_ = routePointsBuilder_.build();
        }
      }

      private void buildPartial0(Route result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.routeType_ = routeType_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Route) {
          return mergeFrom((Route)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Route other) {
        if (other == Route.getDefaultInstance()) return this;
        if (routePointsBuilder_ == null) {
          if (!other.routePoints_.isEmpty()) {
            if (routePoints_.isEmpty()) {
              routePoints_ = other.routePoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRoutePointsIsMutable();
              routePoints_.addAll(other.routePoints_);
            }
            onChanged();
          }
        } else {
          if (!other.routePoints_.isEmpty()) {
            if (routePointsBuilder_.isEmpty()) {
              routePointsBuilder_.dispose();
              routePointsBuilder_ = null;
              routePoints_ = other.routePoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
              routePointsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoutePointsFieldBuilder() : null;
            } else {
              routePointsBuilder_.addAllMessages(other.routePoints_);
            }
          }
        }
        if (other.getRouteType() != 0) {
          setRouteType(other.getRouteType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                RoutePointOuterClass.RoutePoint m =
                    input.readMessage(
                        RoutePointOuterClass.RoutePoint.parser(),
                        extensionRegistry);
                if (routePointsBuilder_ == null) {
                  ensureRoutePointsIsMutable();
                  routePoints_.add(m);
                } else {
                  routePointsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 16: {
                routeType_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<RoutePointOuterClass.RoutePoint> routePoints_ =
        java.util.Collections.emptyList();
      private void ensureRoutePointsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          routePoints_ = new java.util.ArrayList<RoutePointOuterClass.RoutePoint>(routePoints_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          RoutePointOuterClass.RoutePoint, RoutePointOuterClass.RoutePoint.Builder, RoutePointOuterClass.RoutePointOrBuilder> routePointsBuilder_;

      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public java.util.List<RoutePointOuterClass.RoutePoint> getRoutePointsList() {
        if (routePointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routePoints_);
        } else {
          return routePointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public int getRoutePointsCount() {
        if (routePointsBuilder_ == null) {
          return routePoints_.size();
        } else {
          return routePointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public RoutePointOuterClass.RoutePoint getRoutePoints(int index) {
        if (routePointsBuilder_ == null) {
          return routePoints_.get(index);
        } else {
          return routePointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder setRoutePoints(
          int index, RoutePointOuterClass.RoutePoint value) {
        if (routePointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutePointsIsMutable();
          routePoints_.set(index, value);
          onChanged();
        } else {
          routePointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder setRoutePoints(
          int index, RoutePointOuterClass.RoutePoint.Builder builderForValue) {
        if (routePointsBuilder_ == null) {
          ensureRoutePointsIsMutable();
          routePoints_.set(index, builderForValue.build());
          onChanged();
        } else {
          routePointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder addRoutePoints(RoutePointOuterClass.RoutePoint value) {
        if (routePointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutePointsIsMutable();
          routePoints_.add(value);
          onChanged();
        } else {
          routePointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder addRoutePoints(
          int index, RoutePointOuterClass.RoutePoint value) {
        if (routePointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutePointsIsMutable();
          routePoints_.add(index, value);
          onChanged();
        } else {
          routePointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder addRoutePoints(
          RoutePointOuterClass.RoutePoint.Builder builderForValue) {
        if (routePointsBuilder_ == null) {
          ensureRoutePointsIsMutable();
          routePoints_.add(builderForValue.build());
          onChanged();
        } else {
          routePointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder addRoutePoints(
          int index, RoutePointOuterClass.RoutePoint.Builder builderForValue) {
        if (routePointsBuilder_ == null) {
          ensureRoutePointsIsMutable();
          routePoints_.add(index, builderForValue.build());
          onChanged();
        } else {
          routePointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder addAllRoutePoints(
          Iterable<? extends RoutePointOuterClass.RoutePoint> values) {
        if (routePointsBuilder_ == null) {
          ensureRoutePointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, routePoints_);
          onChanged();
        } else {
          routePointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder clearRoutePoints() {
        if (routePointsBuilder_ == null) {
          routePoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          routePointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public Builder removeRoutePoints(int index) {
        if (routePointsBuilder_ == null) {
          ensureRoutePointsIsMutable();
          routePoints_.remove(index);
          onChanged();
        } else {
          routePointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public RoutePointOuterClass.RoutePoint.Builder getRoutePointsBuilder(
          int index) {
        return getRoutePointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public RoutePointOuterClass.RoutePointOrBuilder getRoutePointsOrBuilder(
          int index) {
        if (routePointsBuilder_ == null) {
          return routePoints_.get(index);  } else {
          return routePointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public java.util.List<? extends RoutePointOuterClass.RoutePointOrBuilder>
           getRoutePointsOrBuilderList() {
        if (routePointsBuilder_ != null) {
          return routePointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routePoints_);
        }
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public RoutePointOuterClass.RoutePoint.Builder addRoutePointsBuilder() {
        return getRoutePointsFieldBuilder().addBuilder(
            RoutePointOuterClass.RoutePoint.getDefaultInstance());
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public RoutePointOuterClass.RoutePoint.Builder addRoutePointsBuilder(
          int index) {
        return getRoutePointsFieldBuilder().addBuilder(
            index, RoutePointOuterClass.RoutePoint.getDefaultInstance());
      }
      /**
       * <code>repeated .RoutePoint route_points = 1;</code>
       */
      public java.util.List<RoutePointOuterClass.RoutePoint.Builder>
           getRoutePointsBuilderList() {
        return getRoutePointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          RoutePointOuterClass.RoutePoint, RoutePointOuterClass.RoutePoint.Builder, RoutePointOuterClass.RoutePointOrBuilder>
          getRoutePointsFieldBuilder() {
        if (routePointsBuilder_ == null) {
          routePointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              RoutePointOuterClass.RoutePoint, RoutePointOuterClass.RoutePoint.Builder, RoutePointOuterClass.RoutePointOrBuilder>(
                  routePoints_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          routePoints_ = null;
        }
        return routePointsBuilder_;
      }

      private int routeType_ ;
      /**
       * <code>uint32 route_type = 2;</code>
       * @return The routeType.
       */
      @Override
      public int getRouteType() {
        return routeType_;
      }
      /**
       * <code>uint32 route_type = 2;</code>
       * @param value The routeType to set.
       * @return This builder for chaining.
       */
      public Builder setRouteType(int value) {

        routeType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 route_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRouteType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        routeType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Route)
    }

    // @@protoc_insertion_point(class_scope:Route)
    private static final Route DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Route();
    }

    public static Route getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Route>
        PARSER = new com.google.protobuf.AbstractParser<Route>() {
      @Override
      public Route parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Route> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Route> getParserForType() {
      return PARSER;
    }

    @Override
    public Route getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Route_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Route_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Route.proto\032\020RoutePoint.proto\">\n\005Route" +
      "\022!\n\014route_points\030\001 \003(\0132\013.RoutePoint\022\022\n\nr" +
      "oute_type\030\002 \001(\rB\032\n\030io.irminsul.common.pr" +
      "otob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          RoutePointOuterClass.getDescriptor(),
        });
    internal_static_Route_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Route_descriptor,
        new String[] { "RoutePoints", "RouteType", });
    descriptor.resolveAllFeaturesImmutable();
    RoutePointOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
